---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "health-checks-ui-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "health-checks-ui"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "80"
      targetPort: "80"
