---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gateway
          resources:
            limits:
              memory: 512Mi
          image: gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: gateway-env
            - secretRef:
                name: gateway-secrets
      terminationGracePeriodSeconds: 180
