global using System.Net.Mime;
global using System.Text;
global using BookWorm.Agent.Book;
global using BookWorm.Agent.Book.Extensions;
global using BookWorm.ServiceDefaults;
global using BookWorm.ServiceDefaults.ApiSpecification.OpenApi;
global using BookWorm.SharedKernel.Models;
global using Microsoft.SemanticKernel;
global using Microsoft.SemanticKernel.ChatCompletion;
