---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  serviceName: "ollama"
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ollama
          image: docker.io/ollama/ollama:0.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11434
          envFrom:
            - configMapRef:
                name: ollama-env
          resources:
            requests:
              cpu: "1500m"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
              ephemeral-storage: "4Gi"
          volumeMounts:
            - name: bookworm-apphost-62fd53aa4e-ollama-ollama
              mountPath: /root/.ollama
  volumeClaimTemplates:
    - metadata:
        name: bookworm-apphost-62fd53aa4e-ollama-ollama
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi
