name: "Format"
description: "Format the repository using Husky"

inputs:
  dotnet-version:
    description: "The version of .NET Core to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: Install Tools
      shell: bash
      run: dotnet tool restore

    - name: Configure Husky
      shell: bash
      if: success()
      run: dotnet husky install

    - name: Run Format Task
      shell: bash
      if: success()
      run: dotnet husky run --name format
