global using System.Diagnostics;
global using BookWorm.Constants;
global using BookWorm.Identity.Data;
global using BookWorm.Identity.Models;
global using BookWorm.ServiceDefaults;
global using Duende.IdentityServer;
global using Duende.IdentityServer.Models;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
