---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "bookworm-basket-config"
  labels:
    app: "aspire"
    component: "bookworm-basket"
data:
  ASPNETCORE_URLS: "{{ .Values.config.bookworm-basket.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-basket.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-basket.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.bookworm-basket.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.bookworm-basket.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.bookworm-basket.HTTP_PORTS }}"
  ConnectionStrings__redis: "{{ .Values.config.bookworm-basket.ConnectionStrings__redis }}"
  services__keycloak__http__0: "{{ .Values.config.bookworm-basket.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.bookworm-basket.services__keycloak__management__0 }}"
  services__bookworm_catalog__http__0: "{{ .Values.config.bookworm-basket.services__bookworm_catalog__http__0 }}"
  services__bookworm_catalog__https__0: "{{ .Values.config.bookworm-basket.services__bookworm_catalog__https__0 }}"
  services__bookworm_catalog__healthchecks__0: "{{ .Values.config.bookworm-basket.services__bookworm_catalog__healthchecks__0 }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.bookworm-basket.HEALTHCHECKSUI_URLS }}"
