---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bookworm-basket-secrets"
  labels:
    app: "aspire"
    component: "bookworm-basket"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.bookworm-basket.queue_password }}@queue:5672"
type: "Opaque"
