---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8084
      targetPort: 8080
    - name: management
      port: 9000
      targetPort: 9000
