---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: "keycloak"
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      automountServiceAccountToken: false
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          imagePullPolicy: IfNotPresent
          args:
            - "start"
            - "--import-realm"
          ports:
            - containerPort: 8080
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: keycloak-env
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: bookworm-apphost-62fd53aa4e-keycloak-data
              mountPath: /opt/keycloak/data
  volumeClaimTemplates:
    - metadata:
        name: bookworm-apphost-62fd53aa4e-keycloak-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
