---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ollama-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "ollama"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "11434"
      targetPort: "11434"
