---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "ollama-statefulset"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "ollama"
    spec:
      containers:
        - image: "docker.io/ollama/ollama:0.6.0"
          name: "ollama"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "11434"
          volumeMounts:
            - name: "bookworm.apphost-62fd53aa4e-ollama-ollama"
              mountPath: "/root/.ollama"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "bookworm.apphost-62fd53aa4e-ollama-ollama"
          emptyDir: {}
  selector:
    matchLabels:
      app: "aspire"
      component: "ollama"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
