# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
tone_instructions: |
  Expert .NET/C# 13 reviewer. Focus on Clean Architecture, DDD, SOLID principles, security, performance, and enterprise patterns.
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  path_instructions:
    - path: "src/Services/**/Domain/**"
      instructions: |
        Focus on Domain-Driven Design principles:
        - Ensure entities have proper encapsulation and business logic
        - Validate domain invariants and business rules
        - Check for proper aggregate boundaries and consistency
        - Review value objects for immutability
    - path: "src/Services/**/Application/**"
      instructions: |
        Review application layer concerns:
        - CQRS command/query separation
        - Proper use of MediatR patterns
        - Input validation and error handling
        - Transaction boundaries and data consistency
    - path: "src/Services/**/Infrastructure/**"
      instructions: |
        Examine infrastructure implementations:
        - Repository pattern adherence
        - Database migrations and EF Core configurations
        - External service integrations
        - Caching strategies and performance
    - path: "src/Services/**/Presentation/**"
      instructions: |
        API and presentation layer review:
        - RESTful API design principles
        - OpenAPI documentation completeness
        - Input validation and security
        - Error handling and status codes
    - path: "**/*Tests/**"
      instructions: |
        Test quality assessment:
        - Test coverage and meaningful assertions
        - AAA pattern (Arrange, Act, Assert)
        - Test isolation and determinism
        - Integration test setup and teardown
    - path: "src/Aspire/**"
      instructions: |
        .NET Aspire orchestration review:
        - Service discovery and configuration
        - Health checks and observability
        - Resource allocation and scaling
        - Development environment setup
chat:
  auto_reply: true
