title = "gitleaks config"

[allowlist]
description = "global allow lists"
paths = [
	'''gitleaks.toml''',
	'''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe)$''',
	'''node_modules''',
	'''package-lock.json''',
	'''Database.refactorlog''',
	'''vendor''',
]
