<Project>
  <PropertyGroup Label="Package Versions">
    <!-- Core Libraries -->
    <AspireVersion>13.6.1</AspireVersion>
    <AspireUnstableVersion>$(AspireVersion)-preview.1.26506.6</AspireUnstableVersion>
    <DotnetPackagesVersion>10.0.12</DotnetPackagesVersion>
    <GrpcVersion>2.84.0</GrpcVersion>
    <!-- Integration Libraries -->
    <WolverineVersion>6.48.2</WolverineVersion>
    <QuartzVersion>4.4.0</QuartzVersion>
    <FusionCacheVersion>2.9.0</FusionCacheVersion>
    <!-- Microsoft Packages -->
    <MsExtVersion>10.10.0</MsExtVersion>
    <MsTestVersion>2.5.1</MsTestVersion>
    <ToolKitVersion>13.6.0</ToolKitVersion>
    <!-- Agent Framework Packages -->
    <AgentFrameworkVersion>1.24.0</AgentFrameworkVersion>
    <AgentFrameworkUnstableVersion>$(AgentFrameworkVersion)-preview.261006.1</AgentFrameworkUnstableVersion>
    <AgentFrameworkAlphaVersion>$(AgentFrameworkVersion)-alpha.261006.1</AgentFrameworkAlphaVersion>
    <!-- Miscellaneous Packages -->
    <HealthChecksVersion>9.0.0</HealthChecksVersion>
  </PropertyGroup>
</Project>
