<Project>
  <PropertyGroup Label="Package Versions">
    <!-- Core Libraries -->
    <AspireVersion>13.5.4</AspireVersion>
    <AspireUnstableVersion>$(AspireVersion)-preview.1.26464.4</AspireUnstableVersion>
    <DotnetPackagesVersion>10.0.12</DotnetPackagesVersion>
    <GrpcVersion>2.84.0</GrpcVersion>
    <!-- Integration Libraries -->
    <WolverineVersion>6.39.1</WolverineVersion>
    <TUnitVersion>1.69.0</TUnitVersion>
    <QuartzVersion>4.1.1</QuartzVersion>
    <FusionCacheVersion>2.9.0</FusionCacheVersion>
    <!-- Microsoft Packages -->
    <MsExtVersion>10.10.0</MsExtVersion>
    <MsTestVersion>2.4.1</MsTestVersion>
    <ToolKitVersion>13.5.0</ToolKitVersion>
    <AgentFrameworkVersion>1.22.0</AgentFrameworkVersion>
    <AgentFrameworkUnstableVersion>$(AgentFrameworkVersion)-preview.260918.1</AgentFrameworkUnstableVersion>
    <!-- Observability & Health -->
    <HealthChecksVersion>9.0.0</HealthChecksVersion>
    <OtelVersion>1.19.1</OtelVersion>
    <OtelUnstableVersion>$(OtelVersion)-beta.1</OtelUnstableVersion>
  </PropertyGroup>
</Project>
