// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BookWorm.Ordering.Infrastructure.Data.CompiledModels
{
    public partial class OrderingContextModel
    {
        partial void Initialize()
        {
            var address = AddressEntityType.Create(this);
            var buyer = BuyerEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderItem = OrderItemEntityType.Create(this);
            var inboxState = InboxStateEntityType.Create(this);
            var outboxMessage = OutboxMessageEntityType.Create(this);
            var outboxState = OutboxStateEntityType.Create(this);

            AddressEntityType.CreateForeignKey1(address, buyer);
            OrderEntityType.CreateForeignKey1(order, buyer);
            OrderItemEntityType.CreateForeignKey1(orderItem, order);

            AddressEntityType.CreateAnnotations(address);
            BuyerEntityType.CreateAnnotations(buyer);
            OrderEntityType.CreateAnnotations(order);
            OrderItemEntityType.CreateAnnotations(orderItem);
            InboxStateEntityType.CreateAnnotations(inboxState);
            OutboxMessageEntityType.CreateAnnotations(outboxMessage);
            OutboxStateEntityType.CreateAnnotations(outboxState);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "8.0.7");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var address = FindEntityType("BookWorm.Ordering.Domain.BuyerAggregate.Address")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            address.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var bookWormOrderingDomainBuyerAggregateAddressTableBase = new TableBase("BookWorm.Ordering.Domain.BuyerAggregate.Address", null, relationalModel);
            var address_cityColumnBase = new ColumnBase<ColumnMappingBase>("address_city", "character varying(50)", bookWormOrderingDomainBuyerAggregateAddressTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainBuyerAggregateAddressTableBase.Columns.Add("address_city", address_cityColumnBase);
            var address_provinceColumnBase = new ColumnBase<ColumnMappingBase>("address_province", "character varying(50)", bookWormOrderingDomainBuyerAggregateAddressTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainBuyerAggregateAddressTableBase.Columns.Add("address_province", address_provinceColumnBase);
            var address_streetColumnBase = new ColumnBase<ColumnMappingBase>("address_street", "character varying(50)", bookWormOrderingDomainBuyerAggregateAddressTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainBuyerAggregateAddressTableBase.Columns.Add("address_street", address_streetColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("id", "uuid", bookWormOrderingDomainBuyerAggregateAddressTableBase);
            bookWormOrderingDomainBuyerAggregateAddressTableBase.Columns.Add("id", idColumnBase);
            relationalModel.DefaultTables.Add("BookWorm.Ordering.Domain.BuyerAggregate.Address", bookWormOrderingDomainBuyerAggregateAddressTableBase);
            var bookWormOrderingDomainBuyerAggregateAddressMappingBase = new TableMappingBase<ColumnMappingBase>(address, bookWormOrderingDomainBuyerAggregateAddressTableBase, true);
            bookWormOrderingDomainBuyerAggregateAddressTableBase.AddTypeMapping(bookWormOrderingDomainBuyerAggregateAddressMappingBase, false);
            defaultTableMappings.Add(bookWormOrderingDomainBuyerAggregateAddressMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, address.FindProperty("BuyerId")!, bookWormOrderingDomainBuyerAggregateAddressMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)address_cityColumnBase, address.FindProperty("City")!, bookWormOrderingDomainBuyerAggregateAddressMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)address_provinceColumnBase, address.FindProperty("Province")!, bookWormOrderingDomainBuyerAggregateAddressMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)address_streetColumnBase, address.FindProperty("Street")!, bookWormOrderingDomainBuyerAggregateAddressMappingBase);

            var tableMappings = new List<TableMapping>();
            address.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var buyersTable = new Table("buyers", null, relationalModel);
            var idColumn = new Column("id", "uuid", buyersTable);
            buyersTable.Columns.Add("id", idColumn);
            var address_cityColumn = new Column("address_city", "character varying(50)", buyersTable)
            {
                IsNullable = true
            };
            buyersTable.Columns.Add("address_city", address_cityColumn);
            var address_provinceColumn = new Column("address_province", "character varying(50)", buyersTable)
            {
                IsNullable = true
            };
            buyersTable.Columns.Add("address_province", address_provinceColumn);
            var address_streetColumn = new Column("address_street", "character varying(50)", buyersTable)
            {
                IsNullable = true
            };
            buyersTable.Columns.Add("address_street", address_streetColumn);
            var created_dateColumn = new Column("created_date", "timestamp with time zone", buyersTable);
            buyersTable.Columns.Add("created_date", created_dateColumn);
            var nameColumn = new Column("name", "character varying(20)", buyersTable);
            buyersTable.Columns.Add("name", nameColumn);
            var update_dateColumn = new Column("update_date", "timestamp with time zone", buyersTable)
            {
                IsNullable = true
            };
            buyersTable.Columns.Add("update_date", update_dateColumn);
            var versionColumn = new Column("version", "uuid", buyersTable);
            buyersTable.Columns.Add("version", versionColumn);
            var pk_buyers = new UniqueConstraint("pk_buyers", buyersTable, new[] { idColumn });
            buyersTable.PrimaryKey = pk_buyers;
            var pk_buyersUc = RelationalModel.GetKey(this,
                "BookWorm.Ordering.Domain.BuyerAggregate.Address",
                new[] { "BuyerId" });
            pk_buyers.MappedKeys.Add(pk_buyersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_buyersUc).Add(pk_buyers);
            var pk_buyersUc0 = RelationalModel.GetKey(this,
                "BookWorm.Ordering.Domain.BuyerAggregate.Buyer",
                new[] { "Id" });
            pk_buyers.MappedKeys.Add(pk_buyersUc0);
            RelationalModel.GetOrCreateUniqueConstraints(pk_buyersUc0).Add(pk_buyers);
            buyersTable.UniqueConstraints.Add("pk_buyers", pk_buyers);
            relationalModel.Tables.Add(("buyers", null), buyersTable);
            var buyersTableMapping = new TableMapping(address, buyersTable, true)
            {
                IsSharedTablePrincipal = false,
            };
            buyersTable.AddTypeMapping(buyersTableMapping, true);
            tableMappings.Add(buyersTableMapping);
            buyersTable.AddRowInternalForeignKey(address, RelationalModel.GetForeignKey(this,
                "BookWorm.Ordering.Domain.BuyerAggregate.Address",
                new[] { "BuyerId" },
                "BookWorm.Ordering.Domain.BuyerAggregate.Buyer",
                new[] { "Id" }));
            RelationalModel.CreateColumnMapping(idColumn, address.FindProperty("BuyerId")!, buyersTableMapping);
            RelationalModel.CreateColumnMapping(address_cityColumn, address.FindProperty("City")!, buyersTableMapping);
            RelationalModel.CreateColumnMapping(address_provinceColumn, address.FindProperty("Province")!, buyersTableMapping);
            RelationalModel.CreateColumnMapping(address_streetColumn, address.FindProperty("Street")!, buyersTableMapping);

            var buyer = FindEntityType("BookWorm.Ordering.Domain.BuyerAggregate.Buyer")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            buyer.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var bookWormOrderingDomainBuyerAggregateBuyerTableBase = new TableBase("BookWorm.Ordering.Domain.BuyerAggregate.Buyer", null, relationalModel);
            var created_dateColumnBase = new ColumnBase<ColumnMappingBase>("created_date", "timestamp with time zone", bookWormOrderingDomainBuyerAggregateBuyerTableBase);
            bookWormOrderingDomainBuyerAggregateBuyerTableBase.Columns.Add("created_date", created_dateColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("id", "uuid", bookWormOrderingDomainBuyerAggregateBuyerTableBase);
            bookWormOrderingDomainBuyerAggregateBuyerTableBase.Columns.Add("id", idColumnBase0);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("name", "character varying(20)", bookWormOrderingDomainBuyerAggregateBuyerTableBase);
            bookWormOrderingDomainBuyerAggregateBuyerTableBase.Columns.Add("name", nameColumnBase);
            var update_dateColumnBase = new ColumnBase<ColumnMappingBase>("update_date", "timestamp with time zone", bookWormOrderingDomainBuyerAggregateBuyerTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainBuyerAggregateBuyerTableBase.Columns.Add("update_date", update_dateColumnBase);
            var versionColumnBase = new ColumnBase<ColumnMappingBase>("version", "uuid", bookWormOrderingDomainBuyerAggregateBuyerTableBase);
            bookWormOrderingDomainBuyerAggregateBuyerTableBase.Columns.Add("version", versionColumnBase);
            relationalModel.DefaultTables.Add("BookWorm.Ordering.Domain.BuyerAggregate.Buyer", bookWormOrderingDomainBuyerAggregateBuyerTableBase);
            var bookWormOrderingDomainBuyerAggregateBuyerMappingBase = new TableMappingBase<ColumnMappingBase>(buyer, bookWormOrderingDomainBuyerAggregateBuyerTableBase, true);
            bookWormOrderingDomainBuyerAggregateBuyerTableBase.AddTypeMapping(bookWormOrderingDomainBuyerAggregateBuyerMappingBase, false);
            defaultTableMappings0.Add(bookWormOrderingDomainBuyerAggregateBuyerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, buyer.FindProperty("Id")!, bookWormOrderingDomainBuyerAggregateBuyerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)created_dateColumnBase, buyer.FindProperty("CreatedDate")!, bookWormOrderingDomainBuyerAggregateBuyerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, buyer.FindProperty("Name")!, bookWormOrderingDomainBuyerAggregateBuyerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)update_dateColumnBase, buyer.FindProperty("UpdateDate")!, bookWormOrderingDomainBuyerAggregateBuyerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)versionColumnBase, buyer.FindProperty("Version")!, bookWormOrderingDomainBuyerAggregateBuyerMappingBase);

            var tableMappings0 = new List<TableMapping>();
            buyer.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var buyersTableMapping0 = new TableMapping(buyer, buyersTable, true)
            {
                IsSharedTablePrincipal = true,
            };
            buyersTable.AddTypeMapping(buyersTableMapping0, false);
            tableMappings0.Add(buyersTableMapping0);
            RelationalModel.CreateColumnMapping(idColumn, buyer.FindProperty("Id")!, buyersTableMapping0);
            RelationalModel.CreateColumnMapping(created_dateColumn, buyer.FindProperty("CreatedDate")!, buyersTableMapping0);
            RelationalModel.CreateColumnMapping(nameColumn, buyer.FindProperty("Name")!, buyersTableMapping0);
            RelationalModel.CreateColumnMapping(update_dateColumn, buyer.FindProperty("UpdateDate")!, buyersTableMapping0);
            RelationalModel.CreateColumnMapping(versionColumn, buyer.FindProperty("Version")!, buyersTableMapping0);

            var order = FindEntityType("BookWorm.Ordering.Domain.OrderAggregate.Order")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            order.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var bookWormOrderingDomainOrderAggregateOrderTableBase = new TableBase("BookWorm.Ordering.Domain.OrderAggregate.Order", null, relationalModel);
            var buyer_idColumnBase = new ColumnBase<ColumnMappingBase>("buyer_id", "uuid", bookWormOrderingDomainOrderAggregateOrderTableBase);
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("buyer_id", buyer_idColumnBase);
            var created_dateColumnBase0 = new ColumnBase<ColumnMappingBase>("created_date", "timestamp with time zone", bookWormOrderingDomainOrderAggregateOrderTableBase);
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("created_date", created_dateColumnBase0);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("id", "uuid", bookWormOrderingDomainOrderAggregateOrderTableBase);
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("id", idColumnBase1);
            var noteColumnBase = new ColumnBase<ColumnMappingBase>("note", "character varying(500)", bookWormOrderingDomainOrderAggregateOrderTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("note", noteColumnBase);
            var statusColumnBase = new ColumnBase<ColumnMappingBase>("status", "smallint", bookWormOrderingDomainOrderAggregateOrderTableBase);
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("status", statusColumnBase);
            var update_dateColumnBase0 = new ColumnBase<ColumnMappingBase>("update_date", "timestamp with time zone", bookWormOrderingDomainOrderAggregateOrderTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("update_date", update_dateColumnBase0);
            var versionColumnBase0 = new ColumnBase<ColumnMappingBase>("version", "uuid", bookWormOrderingDomainOrderAggregateOrderTableBase);
            bookWormOrderingDomainOrderAggregateOrderTableBase.Columns.Add("version", versionColumnBase0);
            relationalModel.DefaultTables.Add("BookWorm.Ordering.Domain.OrderAggregate.Order", bookWormOrderingDomainOrderAggregateOrderTableBase);
            var bookWormOrderingDomainOrderAggregateOrderMappingBase = new TableMappingBase<ColumnMappingBase>(order, bookWormOrderingDomainOrderAggregateOrderTableBase, true);
            bookWormOrderingDomainOrderAggregateOrderTableBase.AddTypeMapping(bookWormOrderingDomainOrderAggregateOrderMappingBase, false);
            defaultTableMappings1.Add(bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, order.FindProperty("Id")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)buyer_idColumnBase, order.FindProperty("BuyerId")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)created_dateColumnBase0, order.FindProperty("CreatedDate")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)noteColumnBase, order.FindProperty("Note")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)statusColumnBase, order.FindProperty("Status")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)update_dateColumnBase0, order.FindProperty("UpdateDate")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)versionColumnBase0, order.FindProperty("Version")!, bookWormOrderingDomainOrderAggregateOrderMappingBase);

            var tableMappings1 = new List<TableMapping>();
            order.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var ordersTable = new Table("orders", null, relationalModel);
            var idColumn0 = new Column("id", "uuid", ordersTable);
            ordersTable.Columns.Add("id", idColumn0);
            var buyer_idColumn = new Column("buyer_id", "uuid", ordersTable);
            ordersTable.Columns.Add("buyer_id", buyer_idColumn);
            var created_dateColumn0 = new Column("created_date", "timestamp with time zone", ordersTable);
            ordersTable.Columns.Add("created_date", created_dateColumn0);
            var noteColumn = new Column("note", "character varying(500)", ordersTable)
            {
                IsNullable = true
            };
            ordersTable.Columns.Add("note", noteColumn);
            var statusColumn = new Column("status", "smallint", ordersTable);
            ordersTable.Columns.Add("status", statusColumn);
            var update_dateColumn0 = new Column("update_date", "timestamp with time zone", ordersTable)
            {
                IsNullable = true
            };
            ordersTable.Columns.Add("update_date", update_dateColumn0);
            var versionColumn0 = new Column("version", "uuid", ordersTable);
            ordersTable.Columns.Add("version", versionColumn0);
            var pk_orders = new UniqueConstraint("pk_orders", ordersTable, new[] { idColumn0 });
            ordersTable.PrimaryKey = pk_orders;
            var pk_ordersUc = RelationalModel.GetKey(this,
                "BookWorm.Ordering.Domain.OrderAggregate.Order",
                new[] { "Id" });
            pk_orders.MappedKeys.Add(pk_ordersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_ordersUc).Add(pk_orders);
            ordersTable.UniqueConstraints.Add("pk_orders", pk_orders);
            var ix_orders_buyer_id = new TableIndex(
            "ix_orders_buyer_id", ordersTable, new[] { buyer_idColumn }, false);
            var ix_orders_buyer_idIx = RelationalModel.GetIndex(this,
                "BookWorm.Ordering.Domain.OrderAggregate.Order",
                new[] { "BuyerId" });
            ix_orders_buyer_id.MappedIndexes.Add(ix_orders_buyer_idIx);
            RelationalModel.GetOrCreateTableIndexes(ix_orders_buyer_idIx).Add(ix_orders_buyer_id);
            ordersTable.Indexes.Add("ix_orders_buyer_id", ix_orders_buyer_id);
            relationalModel.Tables.Add(("orders", null), ordersTable);
            var ordersTableMapping = new TableMapping(order, ordersTable, true);
            ordersTable.AddTypeMapping(ordersTableMapping, false);
            tableMappings1.Add(ordersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, order.FindProperty("Id")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(buyer_idColumn, order.FindProperty("BuyerId")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(created_dateColumn0, order.FindProperty("CreatedDate")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(noteColumn, order.FindProperty("Note")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(statusColumn, order.FindProperty("Status")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(update_dateColumn0, order.FindProperty("UpdateDate")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(versionColumn0, order.FindProperty("Version")!, ordersTableMapping);

            var orderItem = FindEntityType("BookWorm.Ordering.Domain.OrderAggregate.OrderItem")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            orderItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var bookWormOrderingDomainOrderAggregateOrderItemTableBase = new TableBase("BookWorm.Ordering.Domain.OrderAggregate.OrderItem", null, relationalModel);
            var book_idColumnBase = new ColumnBase<ColumnMappingBase>("book_id", "uuid", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("book_id", book_idColumnBase);
            var created_dateColumnBase1 = new ColumnBase<ColumnMappingBase>("created_date", "timestamp with time zone", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("created_date", created_dateColumnBase1);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("id", "uuid", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("id", idColumnBase2);
            var order_idColumnBase = new ColumnBase<ColumnMappingBase>("order_id", "uuid", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("order_id", order_idColumnBase);
            var priceColumnBase = new ColumnBase<ColumnMappingBase>("price", "numeric", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("price", priceColumnBase);
            var quantityColumnBase = new ColumnBase<ColumnMappingBase>("quantity", "integer", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("quantity", quantityColumnBase);
            var update_dateColumnBase1 = new ColumnBase<ColumnMappingBase>("update_date", "timestamp with time zone", bookWormOrderingDomainOrderAggregateOrderItemTableBase)
            {
                IsNullable = true
            };
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("update_date", update_dateColumnBase1);
            var versionColumnBase1 = new ColumnBase<ColumnMappingBase>("version", "uuid", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.Columns.Add("version", versionColumnBase1);
            relationalModel.DefaultTables.Add("BookWorm.Ordering.Domain.OrderAggregate.OrderItem", bookWormOrderingDomainOrderAggregateOrderItemTableBase);
            var bookWormOrderingDomainOrderAggregateOrderItemMappingBase = new TableMappingBase<ColumnMappingBase>(orderItem, bookWormOrderingDomainOrderAggregateOrderItemTableBase, true);
            bookWormOrderingDomainOrderAggregateOrderItemTableBase.AddTypeMapping(bookWormOrderingDomainOrderAggregateOrderItemMappingBase, false);
            defaultTableMappings2.Add(bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, orderItem.FindProperty("Id")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)book_idColumnBase, orderItem.FindProperty("BookId")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)created_dateColumnBase1, orderItem.FindProperty("CreatedDate")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)order_idColumnBase, orderItem.FindProperty("OrderId")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)priceColumnBase, orderItem.FindProperty("Price")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityColumnBase, orderItem.FindProperty("Quantity")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)update_dateColumnBase1, orderItem.FindProperty("UpdateDate")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)versionColumnBase1, orderItem.FindProperty("Version")!, bookWormOrderingDomainOrderAggregateOrderItemMappingBase);

            var tableMappings2 = new List<TableMapping>();
            orderItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var order_itemsTable = new Table("order_items", null, relationalModel);
            var idColumn1 = new Column("id", "uuid", order_itemsTable);
            order_itemsTable.Columns.Add("id", idColumn1);
            var book_idColumn = new Column("book_id", "uuid", order_itemsTable);
            order_itemsTable.Columns.Add("book_id", book_idColumn);
            var created_dateColumn1 = new Column("created_date", "timestamp with time zone", order_itemsTable);
            order_itemsTable.Columns.Add("created_date", created_dateColumn1);
            var order_idColumn = new Column("order_id", "uuid", order_itemsTable);
            order_itemsTable.Columns.Add("order_id", order_idColumn);
            var priceColumn = new Column("price", "numeric", order_itemsTable);
            order_itemsTable.Columns.Add("price", priceColumn);
            var quantityColumn = new Column("quantity", "integer", order_itemsTable);
            order_itemsTable.Columns.Add("quantity", quantityColumn);
            var update_dateColumn1 = new Column("update_date", "timestamp with time zone", order_itemsTable)
            {
                IsNullable = true
            };
            order_itemsTable.Columns.Add("update_date", update_dateColumn1);
            var versionColumn1 = new Column("version", "uuid", order_itemsTable);
            order_itemsTable.Columns.Add("version", versionColumn1);
            var pk_order_items = new UniqueConstraint("pk_order_items", order_itemsTable, new[] { idColumn1 });
            order_itemsTable.PrimaryKey = pk_order_items;
            var pk_order_itemsUc = RelationalModel.GetKey(this,
                "BookWorm.Ordering.Domain.OrderAggregate.OrderItem",
                new[] { "Id" });
            pk_order_items.MappedKeys.Add(pk_order_itemsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_order_itemsUc).Add(pk_order_items);
            order_itemsTable.UniqueConstraints.Add("pk_order_items", pk_order_items);
            var ix_order_items_order_id = new TableIndex(
            "ix_order_items_order_id", order_itemsTable, new[] { order_idColumn }, false);
            var ix_order_items_order_idIx = RelationalModel.GetIndex(this,
                "BookWorm.Ordering.Domain.OrderAggregate.OrderItem",
                new[] { "OrderId" });
            ix_order_items_order_id.MappedIndexes.Add(ix_order_items_order_idIx);
            RelationalModel.GetOrCreateTableIndexes(ix_order_items_order_idIx).Add(ix_order_items_order_id);
            order_itemsTable.Indexes.Add("ix_order_items_order_id", ix_order_items_order_id);
            relationalModel.Tables.Add(("order_items", null), order_itemsTable);
            var order_itemsTableMapping = new TableMapping(orderItem, order_itemsTable, true);
            order_itemsTable.AddTypeMapping(order_itemsTableMapping, false);
            tableMappings2.Add(order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, orderItem.FindProperty("Id")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(book_idColumn, orderItem.FindProperty("BookId")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(created_dateColumn1, orderItem.FindProperty("CreatedDate")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(order_idColumn, orderItem.FindProperty("OrderId")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(priceColumn, orderItem.FindProperty("Price")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(quantityColumn, orderItem.FindProperty("Quantity")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(update_dateColumn1, orderItem.FindProperty("UpdateDate")!, order_itemsTableMapping);
            RelationalModel.CreateColumnMapping(versionColumn1, orderItem.FindProperty("Version")!, order_itemsTableMapping);

            var inboxState = FindEntityType("MassTransit.EntityFrameworkCoreIntegration.InboxState")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            inboxState.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var massTransitEntityFrameworkCoreIntegrationInboxStateTableBase = new TableBase("MassTransit.EntityFrameworkCoreIntegration.InboxState", null, relationalModel);
            var consumedColumnBase = new ColumnBase<ColumnMappingBase>("consumed", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("consumed", consumedColumnBase);
            var consumer_idColumnBase = new ColumnBase<ColumnMappingBase>("consumer_id", "uuid", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("consumer_id", consumer_idColumnBase);
            var deliveredColumnBase = new ColumnBase<ColumnMappingBase>("delivered", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("delivered", deliveredColumnBase);
            var expiration_timeColumnBase = new ColumnBase<ColumnMappingBase>("expiration_time", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("expiration_time", expiration_timeColumnBase);
            var idColumnBase3 = new ColumnBase<ColumnMappingBase>("id", "bigint", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("id", idColumnBase3);
            var last_sequence_numberColumnBase = new ColumnBase<ColumnMappingBase>("last_sequence_number", "bigint", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("last_sequence_number", last_sequence_numberColumnBase);
            var lock_idColumnBase = new ColumnBase<ColumnMappingBase>("lock_id", "uuid", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("lock_id", lock_idColumnBase);
            var message_idColumnBase = new ColumnBase<ColumnMappingBase>("message_id", "uuid", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("message_id", message_idColumnBase);
            var receive_countColumnBase = new ColumnBase<ColumnMappingBase>("receive_count", "integer", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("receive_count", receive_countColumnBase);
            var receivedColumnBase = new ColumnBase<ColumnMappingBase>("received", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("received", receivedColumnBase);
            var row_versionColumnBase = new ColumnBase<ColumnMappingBase>("row_version", "bytea", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.Columns.Add("row_version", row_versionColumnBase);
            relationalModel.DefaultTables.Add("MassTransit.EntityFrameworkCoreIntegration.InboxState", massTransitEntityFrameworkCoreIntegrationInboxStateTableBase);
            var massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase = new TableMappingBase<ColumnMappingBase>(inboxState, massTransitEntityFrameworkCoreIntegrationInboxStateTableBase, true);
            massTransitEntityFrameworkCoreIntegrationInboxStateTableBase.AddTypeMapping(massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase, false);
            defaultTableMappings3.Add(massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase3, inboxState.FindProperty("Id")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)consumedColumnBase, inboxState.FindProperty("Consumed")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)consumer_idColumnBase, inboxState.FindProperty("ConsumerId")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)deliveredColumnBase, inboxState.FindProperty("Delivered")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expiration_timeColumnBase, inboxState.FindProperty("ExpirationTime")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)last_sequence_numberColumnBase, inboxState.FindProperty("LastSequenceNumber")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lock_idColumnBase, inboxState.FindProperty("LockId")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)message_idColumnBase, inboxState.FindProperty("MessageId")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)receive_countColumnBase, inboxState.FindProperty("ReceiveCount")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)receivedColumnBase, inboxState.FindProperty("Received")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)row_versionColumnBase, inboxState.FindProperty("RowVersion")!, massTransitEntityFrameworkCoreIntegrationInboxStateMappingBase);

            var tableMappings3 = new List<TableMapping>();
            inboxState.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var inbox_stateTable = new Table("inbox_state", null, relationalModel);
            var idColumn2 = new Column("id", "bigint", inbox_stateTable);
            inbox_stateTable.Columns.Add("id", idColumn2);
            idColumn2.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var consumedColumn = new Column("consumed", "timestamp with time zone", inbox_stateTable)
            {
                IsNullable = true
            };
            inbox_stateTable.Columns.Add("consumed", consumedColumn);
            var consumer_idColumn = new Column("consumer_id", "uuid", inbox_stateTable);
            inbox_stateTable.Columns.Add("consumer_id", consumer_idColumn);
            var deliveredColumn = new Column("delivered", "timestamp with time zone", inbox_stateTable)
            {
                IsNullable = true
            };
            inbox_stateTable.Columns.Add("delivered", deliveredColumn);
            var expiration_timeColumn = new Column("expiration_time", "timestamp with time zone", inbox_stateTable)
            {
                IsNullable = true
            };
            inbox_stateTable.Columns.Add("expiration_time", expiration_timeColumn);
            var last_sequence_numberColumn = new Column("last_sequence_number", "bigint", inbox_stateTable)
            {
                IsNullable = true
            };
            inbox_stateTable.Columns.Add("last_sequence_number", last_sequence_numberColumn);
            var lock_idColumn = new Column("lock_id", "uuid", inbox_stateTable);
            inbox_stateTable.Columns.Add("lock_id", lock_idColumn);
            var message_idColumn = new Column("message_id", "uuid", inbox_stateTable);
            inbox_stateTable.Columns.Add("message_id", message_idColumn);
            var receive_countColumn = new Column("receive_count", "integer", inbox_stateTable);
            inbox_stateTable.Columns.Add("receive_count", receive_countColumn);
            var receivedColumn = new Column("received", "timestamp with time zone", inbox_stateTable);
            inbox_stateTable.Columns.Add("received", receivedColumn);
            var row_versionColumn = new Column("row_version", "bytea", inbox_stateTable)
            {
                IsNullable = true
            };
            inbox_stateTable.Columns.Add("row_version", row_versionColumn);
            var ak_inbox_state_message_id_consumer_id = new UniqueConstraint("ak_inbox_state_message_id_consumer_id", inbox_stateTable, new[] { message_idColumn, consumer_idColumn });
            var ak_inbox_state_message_id_consumer_idUc = RelationalModel.GetKey(this,
                "MassTransit.EntityFrameworkCoreIntegration.InboxState",
                new[] { "MessageId", "ConsumerId" });
            ak_inbox_state_message_id_consumer_id.MappedKeys.Add(ak_inbox_state_message_id_consumer_idUc);
            RelationalModel.GetOrCreateUniqueConstraints(ak_inbox_state_message_id_consumer_idUc).Add(ak_inbox_state_message_id_consumer_id);
            inbox_stateTable.UniqueConstraints.Add("ak_inbox_state_message_id_consumer_id", ak_inbox_state_message_id_consumer_id);
            var pk_inbox_state = new UniqueConstraint("pk_inbox_state", inbox_stateTable, new[] { idColumn2 });
            inbox_stateTable.PrimaryKey = pk_inbox_state;
            var pk_inbox_stateUc = RelationalModel.GetKey(this,
                "MassTransit.EntityFrameworkCoreIntegration.InboxState",
                new[] { "Id" });
            pk_inbox_state.MappedKeys.Add(pk_inbox_stateUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_inbox_stateUc).Add(pk_inbox_state);
            inbox_stateTable.UniqueConstraints.Add("pk_inbox_state", pk_inbox_state);
            var ix_inbox_state_delivered = new TableIndex(
            "ix_inbox_state_delivered", inbox_stateTable, new[] { deliveredColumn }, false);
            var ix_inbox_state_deliveredIx = RelationalModel.GetIndex(this,
                "MassTransit.EntityFrameworkCoreIntegration.InboxState",
                new[] { "Delivered" });
            ix_inbox_state_delivered.MappedIndexes.Add(ix_inbox_state_deliveredIx);
            RelationalModel.GetOrCreateTableIndexes(ix_inbox_state_deliveredIx).Add(ix_inbox_state_delivered);
            inbox_stateTable.Indexes.Add("ix_inbox_state_delivered", ix_inbox_state_delivered);
            relationalModel.Tables.Add(("inbox_state", null), inbox_stateTable);
            var inbox_stateTableMapping = new TableMapping(inboxState, inbox_stateTable, true);
            inbox_stateTable.AddTypeMapping(inbox_stateTableMapping, false);
            tableMappings3.Add(inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, inboxState.FindProperty("Id")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(consumedColumn, inboxState.FindProperty("Consumed")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(consumer_idColumn, inboxState.FindProperty("ConsumerId")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(deliveredColumn, inboxState.FindProperty("Delivered")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(expiration_timeColumn, inboxState.FindProperty("ExpirationTime")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(last_sequence_numberColumn, inboxState.FindProperty("LastSequenceNumber")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(lock_idColumn, inboxState.FindProperty("LockId")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(message_idColumn, inboxState.FindProperty("MessageId")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(receive_countColumn, inboxState.FindProperty("ReceiveCount")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(receivedColumn, inboxState.FindProperty("Received")!, inbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(row_versionColumn, inboxState.FindProperty("RowVersion")!, inbox_stateTableMapping);

            var outboxMessage = FindEntityType("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            outboxMessage.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase = new TableBase("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", null, relationalModel);
            var bodyColumnBase = new ColumnBase<ColumnMappingBase>("body", "text", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("body", bodyColumnBase);
            var content_typeColumnBase = new ColumnBase<ColumnMappingBase>("content_type", "character varying(256)", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("content_type", content_typeColumnBase);
            var conversation_idColumnBase = new ColumnBase<ColumnMappingBase>("conversation_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("conversation_id", conversation_idColumnBase);
            var correlation_idColumnBase = new ColumnBase<ColumnMappingBase>("correlation_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("correlation_id", correlation_idColumnBase);
            var destination_addressColumnBase = new ColumnBase<ColumnMappingBase>("destination_address", "character varying(256)", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("destination_address", destination_addressColumnBase);
            var enqueue_timeColumnBase = new ColumnBase<ColumnMappingBase>("enqueue_time", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("enqueue_time", enqueue_timeColumnBase);
            var expiration_timeColumnBase0 = new ColumnBase<ColumnMappingBase>("expiration_time", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("expiration_time", expiration_timeColumnBase0);
            var fault_addressColumnBase = new ColumnBase<ColumnMappingBase>("fault_address", "character varying(256)", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("fault_address", fault_addressColumnBase);
            var headersColumnBase = new ColumnBase<ColumnMappingBase>("headers", "text", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("headers", headersColumnBase);
            var inbox_consumer_idColumnBase = new ColumnBase<ColumnMappingBase>("inbox_consumer_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("inbox_consumer_id", inbox_consumer_idColumnBase);
            var inbox_message_idColumnBase = new ColumnBase<ColumnMappingBase>("inbox_message_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("inbox_message_id", inbox_message_idColumnBase);
            var initiator_idColumnBase = new ColumnBase<ColumnMappingBase>("initiator_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("initiator_id", initiator_idColumnBase);
            var message_idColumnBase0 = new ColumnBase<ColumnMappingBase>("message_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("message_id", message_idColumnBase0);
            var message_typeColumnBase = new ColumnBase<ColumnMappingBase>("message_type", "text", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("message_type", message_typeColumnBase);
            var outbox_idColumnBase = new ColumnBase<ColumnMappingBase>("outbox_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("outbox_id", outbox_idColumnBase);
            var propertiesColumnBase = new ColumnBase<ColumnMappingBase>("properties", "text", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("properties", propertiesColumnBase);
            var request_idColumnBase = new ColumnBase<ColumnMappingBase>("request_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("request_id", request_idColumnBase);
            var response_addressColumnBase = new ColumnBase<ColumnMappingBase>("response_address", "character varying(256)", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("response_address", response_addressColumnBase);
            var sent_timeColumnBase = new ColumnBase<ColumnMappingBase>("sent_time", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("sent_time", sent_timeColumnBase);
            var sequence_numberColumnBase = new ColumnBase<ColumnMappingBase>("sequence_number", "bigint", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("sequence_number", sequence_numberColumnBase);
            var source_addressColumnBase = new ColumnBase<ColumnMappingBase>("source_address", "character varying(256)", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.Columns.Add("source_address", source_addressColumnBase);
            relationalModel.DefaultTables.Add("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase);
            var massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase = new TableMappingBase<ColumnMappingBase>(outboxMessage, massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase, true);
            massTransitEntityFrameworkCoreIntegrationOutboxMessageTableBase.AddTypeMapping(massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase, false);
            defaultTableMappings4.Add(massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sequence_numberColumnBase, outboxMessage.FindProperty("SequenceNumber")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bodyColumnBase, outboxMessage.FindProperty("Body")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)content_typeColumnBase, outboxMessage.FindProperty("ContentType")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)conversation_idColumnBase, outboxMessage.FindProperty("ConversationId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)correlation_idColumnBase, outboxMessage.FindProperty("CorrelationId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)destination_addressColumnBase, outboxMessage.FindProperty("DestinationAddress")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)enqueue_timeColumnBase, outboxMessage.FindProperty("EnqueueTime")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expiration_timeColumnBase0, outboxMessage.FindProperty("ExpirationTime")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fault_addressColumnBase, outboxMessage.FindProperty("FaultAddress")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)headersColumnBase, outboxMessage.FindProperty("Headers")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)inbox_consumer_idColumnBase, outboxMessage.FindProperty("InboxConsumerId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)inbox_message_idColumnBase, outboxMessage.FindProperty("InboxMessageId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)initiator_idColumnBase, outboxMessage.FindProperty("InitiatorId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)message_idColumnBase0, outboxMessage.FindProperty("MessageId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)message_typeColumnBase, outboxMessage.FindProperty("MessageType")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)outbox_idColumnBase, outboxMessage.FindProperty("OutboxId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)propertiesColumnBase, outboxMessage.FindProperty("Properties")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)request_idColumnBase, outboxMessage.FindProperty("RequestId")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)response_addressColumnBase, outboxMessage.FindProperty("ResponseAddress")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sent_timeColumnBase, outboxMessage.FindProperty("SentTime")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)source_addressColumnBase, outboxMessage.FindProperty("SourceAddress")!, massTransitEntityFrameworkCoreIntegrationOutboxMessageMappingBase);

            var tableMappings4 = new List<TableMapping>();
            outboxMessage.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var outbox_messageTable = new Table("outbox_message", null, relationalModel);
            var sequence_numberColumn = new Column("sequence_number", "bigint", outbox_messageTable);
            outbox_messageTable.Columns.Add("sequence_number", sequence_numberColumn);
            sequence_numberColumn.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var bodyColumn = new Column("body", "text", outbox_messageTable);
            outbox_messageTable.Columns.Add("body", bodyColumn);
            var content_typeColumn = new Column("content_type", "character varying(256)", outbox_messageTable);
            outbox_messageTable.Columns.Add("content_type", content_typeColumn);
            var conversation_idColumn = new Column("conversation_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("conversation_id", conversation_idColumn);
            var correlation_idColumn = new Column("correlation_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("correlation_id", correlation_idColumn);
            var destination_addressColumn = new Column("destination_address", "character varying(256)", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("destination_address", destination_addressColumn);
            var enqueue_timeColumn = new Column("enqueue_time", "timestamp with time zone", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("enqueue_time", enqueue_timeColumn);
            var expiration_timeColumn0 = new Column("expiration_time", "timestamp with time zone", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("expiration_time", expiration_timeColumn0);
            var fault_addressColumn = new Column("fault_address", "character varying(256)", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("fault_address", fault_addressColumn);
            var headersColumn = new Column("headers", "text", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("headers", headersColumn);
            var inbox_consumer_idColumn = new Column("inbox_consumer_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("inbox_consumer_id", inbox_consumer_idColumn);
            var inbox_message_idColumn = new Column("inbox_message_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("inbox_message_id", inbox_message_idColumn);
            var initiator_idColumn = new Column("initiator_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("initiator_id", initiator_idColumn);
            var message_idColumn0 = new Column("message_id", "uuid", outbox_messageTable);
            outbox_messageTable.Columns.Add("message_id", message_idColumn0);
            var message_typeColumn = new Column("message_type", "text", outbox_messageTable);
            outbox_messageTable.Columns.Add("message_type", message_typeColumn);
            var outbox_idColumn = new Column("outbox_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("outbox_id", outbox_idColumn);
            var propertiesColumn = new Column("properties", "text", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("properties", propertiesColumn);
            var request_idColumn = new Column("request_id", "uuid", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("request_id", request_idColumn);
            var response_addressColumn = new Column("response_address", "character varying(256)", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("response_address", response_addressColumn);
            var sent_timeColumn = new Column("sent_time", "timestamp with time zone", outbox_messageTable);
            outbox_messageTable.Columns.Add("sent_time", sent_timeColumn);
            var source_addressColumn = new Column("source_address", "character varying(256)", outbox_messageTable)
            {
                IsNullable = true
            };
            outbox_messageTable.Columns.Add("source_address", source_addressColumn);
            var pk_outbox_message = new UniqueConstraint("pk_outbox_message", outbox_messageTable, new[] { sequence_numberColumn });
            outbox_messageTable.PrimaryKey = pk_outbox_message;
            var pk_outbox_messageUc = RelationalModel.GetKey(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxMessage",
                new[] { "SequenceNumber" });
            pk_outbox_message.MappedKeys.Add(pk_outbox_messageUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_outbox_messageUc).Add(pk_outbox_message);
            outbox_messageTable.UniqueConstraints.Add("pk_outbox_message", pk_outbox_message);
            var ix_outbox_message_enqueue_time = new TableIndex(
            "ix_outbox_message_enqueue_time", outbox_messageTable, new[] { enqueue_timeColumn }, false);
            var ix_outbox_message_enqueue_timeIx = RelationalModel.GetIndex(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxMessage",
                new[] { "EnqueueTime" });
            ix_outbox_message_enqueue_time.MappedIndexes.Add(ix_outbox_message_enqueue_timeIx);
            RelationalModel.GetOrCreateTableIndexes(ix_outbox_message_enqueue_timeIx).Add(ix_outbox_message_enqueue_time);
            outbox_messageTable.Indexes.Add("ix_outbox_message_enqueue_time", ix_outbox_message_enqueue_time);
            var ix_outbox_message_expiration_time = new TableIndex(
            "ix_outbox_message_expiration_time", outbox_messageTable, new[] { expiration_timeColumn0 }, false);
            var ix_outbox_message_expiration_timeIx = RelationalModel.GetIndex(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxMessage",
                new[] { "ExpirationTime" });
            ix_outbox_message_expiration_time.MappedIndexes.Add(ix_outbox_message_expiration_timeIx);
            RelationalModel.GetOrCreateTableIndexes(ix_outbox_message_expiration_timeIx).Add(ix_outbox_message_expiration_time);
            outbox_messageTable.Indexes.Add("ix_outbox_message_expiration_time", ix_outbox_message_expiration_time);
            var ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_ = new TableIndex(
            "ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_", outbox_messageTable, new[] { inbox_message_idColumn, inbox_consumer_idColumn, sequence_numberColumn }, true);
            var ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_Ix = RelationalModel.GetIndex(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxMessage",
                new[] { "InboxMessageId", "InboxConsumerId", "SequenceNumber" });
            ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_.MappedIndexes.Add(ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_Ix);
            RelationalModel.GetOrCreateTableIndexes(ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_Ix).Add(ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_);
            outbox_messageTable.Indexes.Add("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_", ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_);
            var ix_outbox_message_outbox_id_sequence_number = new TableIndex(
            "ix_outbox_message_outbox_id_sequence_number", outbox_messageTable, new[] { outbox_idColumn, sequence_numberColumn }, true);
            var ix_outbox_message_outbox_id_sequence_numberIx = RelationalModel.GetIndex(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxMessage",
                new[] { "OutboxId", "SequenceNumber" });
            ix_outbox_message_outbox_id_sequence_number.MappedIndexes.Add(ix_outbox_message_outbox_id_sequence_numberIx);
            RelationalModel.GetOrCreateTableIndexes(ix_outbox_message_outbox_id_sequence_numberIx).Add(ix_outbox_message_outbox_id_sequence_number);
            outbox_messageTable.Indexes.Add("ix_outbox_message_outbox_id_sequence_number", ix_outbox_message_outbox_id_sequence_number);
            relationalModel.Tables.Add(("outbox_message", null), outbox_messageTable);
            var outbox_messageTableMapping = new TableMapping(outboxMessage, outbox_messageTable, true);
            outbox_messageTable.AddTypeMapping(outbox_messageTableMapping, false);
            tableMappings4.Add(outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(sequence_numberColumn, outboxMessage.FindProperty("SequenceNumber")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(bodyColumn, outboxMessage.FindProperty("Body")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(content_typeColumn, outboxMessage.FindProperty("ContentType")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(conversation_idColumn, outboxMessage.FindProperty("ConversationId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(correlation_idColumn, outboxMessage.FindProperty("CorrelationId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(destination_addressColumn, outboxMessage.FindProperty("DestinationAddress")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(enqueue_timeColumn, outboxMessage.FindProperty("EnqueueTime")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(expiration_timeColumn0, outboxMessage.FindProperty("ExpirationTime")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(fault_addressColumn, outboxMessage.FindProperty("FaultAddress")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(headersColumn, outboxMessage.FindProperty("Headers")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(inbox_consumer_idColumn, outboxMessage.FindProperty("InboxConsumerId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(inbox_message_idColumn, outboxMessage.FindProperty("InboxMessageId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(initiator_idColumn, outboxMessage.FindProperty("InitiatorId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(message_idColumn0, outboxMessage.FindProperty("MessageId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(message_typeColumn, outboxMessage.FindProperty("MessageType")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(outbox_idColumn, outboxMessage.FindProperty("OutboxId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(propertiesColumn, outboxMessage.FindProperty("Properties")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(request_idColumn, outboxMessage.FindProperty("RequestId")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(response_addressColumn, outboxMessage.FindProperty("ResponseAddress")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(sent_timeColumn, outboxMessage.FindProperty("SentTime")!, outbox_messageTableMapping);
            RelationalModel.CreateColumnMapping(source_addressColumn, outboxMessage.FindProperty("SourceAddress")!, outbox_messageTableMapping);

            var outboxState = FindEntityType("MassTransit.EntityFrameworkCoreIntegration.OutboxState")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            outboxState.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase = new TableBase("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null, relationalModel);
            var createdColumnBase = new ColumnBase<ColumnMappingBase>("created", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.Columns.Add("created", createdColumnBase);
            var deliveredColumnBase0 = new ColumnBase<ColumnMappingBase>("delivered", "timestamp with time zone", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.Columns.Add("delivered", deliveredColumnBase0);
            var last_sequence_numberColumnBase0 = new ColumnBase<ColumnMappingBase>("last_sequence_number", "bigint", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.Columns.Add("last_sequence_number", last_sequence_numberColumnBase0);
            var lock_idColumnBase0 = new ColumnBase<ColumnMappingBase>("lock_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.Columns.Add("lock_id", lock_idColumnBase0);
            var outbox_idColumnBase0 = new ColumnBase<ColumnMappingBase>("outbox_id", "uuid", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase);
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.Columns.Add("outbox_id", outbox_idColumnBase0);
            var row_versionColumnBase0 = new ColumnBase<ColumnMappingBase>("row_version", "bytea", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase)
            {
                IsNullable = true
            };
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.Columns.Add("row_version", row_versionColumnBase0);
            relationalModel.DefaultTables.Add("MassTransit.EntityFrameworkCoreIntegration.OutboxState", massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase);
            var massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase = new TableMappingBase<ColumnMappingBase>(outboxState, massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase, true);
            massTransitEntityFrameworkCoreIntegrationOutboxStateTableBase.AddTypeMapping(massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase, false);
            defaultTableMappings5.Add(massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)outbox_idColumnBase0, outboxState.FindProperty("OutboxId")!, massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdColumnBase, outboxState.FindProperty("Created")!, massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)deliveredColumnBase0, outboxState.FindProperty("Delivered")!, massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)last_sequence_numberColumnBase0, outboxState.FindProperty("LastSequenceNumber")!, massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lock_idColumnBase0, outboxState.FindProperty("LockId")!, massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)row_versionColumnBase0, outboxState.FindProperty("RowVersion")!, massTransitEntityFrameworkCoreIntegrationOutboxStateMappingBase);

            var tableMappings5 = new List<TableMapping>();
            outboxState.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var outbox_stateTable = new Table("outbox_state", null, relationalModel);
            var outbox_idColumn0 = new Column("outbox_id", "uuid", outbox_stateTable);
            outbox_stateTable.Columns.Add("outbox_id", outbox_idColumn0);
            var createdColumn = new Column("created", "timestamp with time zone", outbox_stateTable);
            outbox_stateTable.Columns.Add("created", createdColumn);
            var deliveredColumn0 = new Column("delivered", "timestamp with time zone", outbox_stateTable)
            {
                IsNullable = true
            };
            outbox_stateTable.Columns.Add("delivered", deliveredColumn0);
            var last_sequence_numberColumn0 = new Column("last_sequence_number", "bigint", outbox_stateTable)
            {
                IsNullable = true
            };
            outbox_stateTable.Columns.Add("last_sequence_number", last_sequence_numberColumn0);
            var lock_idColumn0 = new Column("lock_id", "uuid", outbox_stateTable);
            outbox_stateTable.Columns.Add("lock_id", lock_idColumn0);
            var row_versionColumn0 = new Column("row_version", "bytea", outbox_stateTable)
            {
                IsNullable = true
            };
            outbox_stateTable.Columns.Add("row_version", row_versionColumn0);
            var pk_outbox_state = new UniqueConstraint("pk_outbox_state", outbox_stateTable, new[] { outbox_idColumn0 });
            outbox_stateTable.PrimaryKey = pk_outbox_state;
            var pk_outbox_stateUc = RelationalModel.GetKey(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxState",
                new[] { "OutboxId" });
            pk_outbox_state.MappedKeys.Add(pk_outbox_stateUc);
            RelationalModel.GetOrCreateUniqueConstraints(pk_outbox_stateUc).Add(pk_outbox_state);
            outbox_stateTable.UniqueConstraints.Add("pk_outbox_state", pk_outbox_state);
            var ix_outbox_state_created = new TableIndex(
            "ix_outbox_state_created", outbox_stateTable, new[] { createdColumn }, false);
            var ix_outbox_state_createdIx = RelationalModel.GetIndex(this,
                "MassTransit.EntityFrameworkCoreIntegration.OutboxState",
                new[] { "Created" });
            ix_outbox_state_created.MappedIndexes.Add(ix_outbox_state_createdIx);
            RelationalModel.GetOrCreateTableIndexes(ix_outbox_state_createdIx).Add(ix_outbox_state_created);
            outbox_stateTable.Indexes.Add("ix_outbox_state_created", ix_outbox_state_created);
            relationalModel.Tables.Add(("outbox_state", null), outbox_stateTable);
            var outbox_stateTableMapping = new TableMapping(outboxState, outbox_stateTable, true);
            outbox_stateTable.AddTypeMapping(outbox_stateTableMapping, false);
            tableMappings5.Add(outbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(outbox_idColumn0, outboxState.FindProperty("OutboxId")!, outbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(createdColumn, outboxState.FindProperty("Created")!, outbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(deliveredColumn0, outboxState.FindProperty("Delivered")!, outbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(last_sequence_numberColumn0, outboxState.FindProperty("LastSequenceNumber")!, outbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(lock_idColumn0, outboxState.FindProperty("LockId")!, outbox_stateTableMapping);
            RelationalModel.CreateColumnMapping(row_versionColumn0, outboxState.FindProperty("RowVersion")!, outbox_stateTableMapping);
            var fk_order_items_orders_order_id = new ForeignKeyConstraint(
                "fk_order_items_orders_order_id", order_itemsTable, ordersTable,
                new[] { order_idColumn },
                ordersTable.FindUniqueConstraint("pk_orders")!, ReferentialAction.Cascade);
            var fk_order_items_orders_order_idFk = RelationalModel.GetForeignKey(this,
                "BookWorm.Ordering.Domain.OrderAggregate.OrderItem",
                new[] { "OrderId" },
                "BookWorm.Ordering.Domain.OrderAggregate.Order",
                new[] { "Id" });
            fk_order_items_orders_order_id.MappedForeignKeys.Add(fk_order_items_orders_order_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_order_items_orders_order_idFk).Add(fk_order_items_orders_order_id);
            order_itemsTable.ForeignKeyConstraints.Add(fk_order_items_orders_order_id);
            ordersTable.ReferencingForeignKeyConstraints.Add(fk_order_items_orders_order_id);
            var fk_orders_buyers_buyer_id = new ForeignKeyConstraint(
                "fk_orders_buyers_buyer_id", ordersTable, buyersTable,
                new[] { buyer_idColumn },
                buyersTable.FindUniqueConstraint("pk_buyers")!, ReferentialAction.Cascade);
            var fk_orders_buyers_buyer_idFk = RelationalModel.GetForeignKey(this,
                "BookWorm.Ordering.Domain.OrderAggregate.Order",
                new[] { "BuyerId" },
                "BookWorm.Ordering.Domain.BuyerAggregate.Buyer",
                new[] { "Id" });
            fk_orders_buyers_buyer_id.MappedForeignKeys.Add(fk_orders_buyers_buyer_idFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fk_orders_buyers_buyer_idFk).Add(fk_orders_buyers_buyer_id);
            ordersTable.ForeignKeyConstraints.Add(fk_orders_buyers_buyer_id);
            buyersTable.ReferencingForeignKeyConstraints.Add(fk_orders_buyers_buyer_id);
            return relationalModel.MakeReadOnly();
        }
    }
}
