api-version: 2024-02-02-preview
location: { { .Env.AZURE_LOCATION } }
identity:
  type: UserAssigned
  userAssignedIdentities:
    "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}": {}
properties:
  environmentId: { { .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID } }
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      additionalPortMappings:
        - targetPort: 8081
          external: false
      external: false
      targetPort: { { targetPortOrDefault 8080 } }
      transport: http
      allowInsecure: true
    registries:
      - server: { { .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT } }
        identity: { { .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID } }
    secrets:
      - name: connectionstrings--redis
        value: redis:6379
  template:
    containers:
      - image: { { .Image } }
        name: gateway
        env:
          - name: AZURE_CLIENT_ID
            value: { { .Env.MANAGED_IDENTITY_CLIENT_ID } }
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: ASPNETCORE_HTTP_PORTS
            value: 8080;8081
          - name: BFF__Api__RemoteUrl
            value: https://catalog-api.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}/api/v1/authors
          - name: BFF__Authority
            value: https://identity-api.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: HEALTHCHECKSUI_URLS
            value: http://gateway:8081/healthz
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__redis
            secretRef: connectionstrings--redis
    scale:
      minReplicas: 1
tags:
  azd-service-name: gateway
  aspire-resource-name: gateway
