api-version: 2024-02-02-preview
location: { { .Env.AZURE_LOCATION } }
identity:
  type: UserAssigned
  userAssignedIdentities:
    "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}": {}
properties:
  environmentId: { { .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID } }
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      additionalPortMappings:
        - targetPort: 1025
          external: false
      external: false
      targetPort: 1080
      transport: http
      allowInsecure: true
    registries:
      - server: { { .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT } }
        identity: { { .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID } }
  template:
    containers:
      - image: { { .Image } }
        name: mailserver
        env:
          - name: AZURE_CLIENT_ID
            value: { { .Env.MANAGED_IDENTITY_CLIENT_ID } }
    scale:
      minReplicas: 1
tags:
  azd-service-name: mailserver
  aspire-resource-name: mailserver
