---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "bookworm-ordering-config"
  labels:
    app: "aspire"
    component: "bookworm-ordering"
data:
  ASPNETCORE_URLS: "{{ .Values.config.bookworm-ordering.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-ordering.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-ordering.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.bookworm-ordering.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.bookworm-ordering.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.bookworm-ordering.HTTP_PORTS }}"
  ConnectionStrings__orderingdb: "{{ .Values.config.bookworm-ordering.ConnectionStrings__orderingdb }}"
  services__keycloak__http__0: "{{ .Values.config.bookworm-ordering.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.bookworm-ordering.services__keycloak__management__0 }}"
  ConnectionStrings__redis: "{{ .Values.config.bookworm-ordering.ConnectionStrings__redis }}"
  services__bookworm_catalog__http__0: "{{ .Values.config.bookworm-ordering.services__bookworm_catalog__http__0 }}"
  services__bookworm_catalog__https__0: "{{ .Values.config.bookworm-ordering.services__bookworm_catalog__https__0 }}"
  services__bookworm_catalog__healthchecks__0: "{{ .Values.config.bookworm-ordering.services__bookworm_catalog__healthchecks__0 }}"
  services__bookworm_basket__http__0: "{{ .Values.config.bookworm-ordering.services__bookworm_basket__http__0 }}"
  services__bookworm_basket__https__0: "{{ .Values.config.bookworm-ordering.services__bookworm_basket__https__0 }}"
  services__bookworm_basket__healthchecks__0: "{{ .Values.config.bookworm-ordering.services__bookworm_basket__healthchecks__0 }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.bookworm-ordering.HEALTHCHECKSUI_URLS }}"
