---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bookworm-ordering-secrets"
  labels:
    app: "aspire"
    component: "bookworm-ordering"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.bookworm-ordering.queue_password }}@queue:5672"
type: "Opaque"
