---
apiVersion: v1
kind: Service
metadata:
  name: mailserver
spec:
  type: ClusterIP
  selector:
    app: mailserver
  ports:
    - name: http
      port: 1080
      targetPort: 1080
    - name: smtp
      port: 1025
      targetPort: 1025
