name: "Security Scan"
description: "Run security scanning for secrets detection using Gitleaks"

runs:
  using: "composite"
  steps:
    - name: Run Gitleaks
      shell: bash
      run: |
        docker run --rm -v $(pwd):/repo ghcr.io/gitleaks/gitleaks:v8.27.2 detect --source=/repo --exit-code 0 || echo "Warnings: Potential secrets detected, but continuing CI pipeline"
