---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-basket
  labels:
    app: bookworm-basket
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: bookworm-basket
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookworm-basket
    spec:
      automountServiceAccountToken: false
      containers:
        - name: bookworm-basket
          image: ghcr.io/foxminchan/bookworm/basket:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8001
          livenessProbe:
            httpGet:
              path: /
              port: healthchecks
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /alive
              port: healthchecks
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: "1500m"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
          envFrom:
            - configMapRef:
                name: bookworm-basket-env
            - secretRef:
                name: bookworm-basket-secrets
      terminationGracePeriodSeconds: 180
