---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-catalog
  labels:
    app: bookworm-catalog
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: bookworm-catalog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookworm-catalog
    spec:
      containers:
        - name: bookworm-catalog
          image: bookworm-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: bookworm-catalog-env
            - secretRef:
                name: bookworm-catalog-secrets
      terminationGracePeriodSeconds: 180
