---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mailpit-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "mailpit"
  ports:
    - name: "smtp"
      protocol: "TCP"
      port: "1025"
      targetPort: "1025"
    - name: "http"
      protocol: "TCP"
      port: "8025"
      targetPort: "8025"
