---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mailpit-statefulset"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "mailpit"
    spec:
      containers:
        - image: "docker.io/axllent/mailpit:v1.22.3"
          name: "mailpit"
          ports:
            - name: "smtp"
              protocol: "TCP"
              containerPort: "1025"
            - name: "http"
              protocol: "TCP"
              containerPort: "8025"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app: "aspire"
      component: "mailpit"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
