---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "bookworm-gateway-config"
  labels:
    app: "aspire"
    component: "bookworm-gateway"
data:
  ASPNETCORE_URLS: "{{ .Values.config.bookworm-gateway.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.bookworm-gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.bookworm-gateway.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.bookworm-gateway.HTTP_PORTS }}"
  services__bookworm_catalog__http__0: "{{ .Values.config.bookworm-gateway.services__bookworm_catalog__http__0 }}"
  services__bookworm_catalog__https__0: "{{ .Values.config.bookworm-gateway.services__bookworm_catalog__https__0 }}"
  services__bookworm_catalog__healthchecks__0: "{{ .Values.config.bookworm-gateway.services__bookworm_catalog__healthchecks__0 }}"
  services__bookworm_ordering__http__0: "{{ .Values.config.bookworm-gateway.services__bookworm_ordering__http__0 }}"
  services__bookworm_ordering__https__0: "{{ .Values.config.bookworm-gateway.services__bookworm_ordering__https__0 }}"
  services__bookworm_ordering__healthchecks__0: "{{ .Values.config.bookworm-gateway.services__bookworm_ordering__healthchecks__0 }}"
  services__bookworm_rating__http__0: "{{ .Values.config.bookworm-gateway.services__bookworm_rating__http__0 }}"
  services__bookworm_rating__https__0: "{{ .Values.config.bookworm-gateway.services__bookworm_rating__https__0 }}"
  services__bookworm_rating__healthchecks__0: "{{ .Values.config.bookworm-gateway.services__bookworm_rating__healthchecks__0 }}"
  services__bookworm_basket__http__0: "{{ .Values.config.bookworm-gateway.services__bookworm_basket__http__0 }}"
  services__bookworm_basket__https__0: "{{ .Values.config.bookworm-gateway.services__bookworm_basket__https__0 }}"
  services__bookworm_basket__healthchecks__0: "{{ .Values.config.bookworm-gateway.services__bookworm_basket__healthchecks__0 }}"
  services__bookworm_finance__http__0: "{{ .Values.config.bookworm-gateway.services__bookworm_finance__http__0 }}"
  services__bookworm_finance__https__0: "{{ .Values.config.bookworm-gateway.services__bookworm_finance__https__0 }}"
  services__bookworm_finance__healthchecks__0: "{{ .Values.config.bookworm-gateway.services__bookworm_finance__healthchecks__0 }}"
  services__keycloak__http__0: "{{ .Values.config.bookworm-gateway.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.bookworm-gateway.services__keycloak__management__0 }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.bookworm-gateway.HEALTHCHECKSUI_URLS }}"
