name: "Publish Artifact"
description: "Publish the artifact to GitHub Container Registry"

inputs:
  global-json-file:
    description: "The path to the global.json file"
    required: false
    default: "./global.json"
  bun-version-file:
    description: "The path to the .bun-version file"
    required: false
    default: ".bun-version"
  repository-owner:
    description: "The owner of the repository"
    required: true
    default: "${{ github.repository_owner }}"
  repository-name:
    description: "The name of the repository"
    required: true
    default: "${{ github.event.repository.name }}"
  operations-environment:
    description: "The operations environment to use for Aspire commands"
    required: false
    default: ${{ runner.os }}
  openai-apikey:
    description: "OpenAI API Key"
    required: false
  kc-url:
    description: "Keycloak URL"
    required: false
  kc-realm:
    description: "Keycloak Realm"
    required: false
  catalog-secret:
    description: "Catalog Service Client Secret"
    required: false
  basket-secret:
    description: "Basket Service Client Secret"
    required: false
  ordering-secret:
    description: "Ordering Service Client Secret"
    required: false
  chatting-secret:
    description: "Chatting Service Client Secret"
    required: false
  rating-secret:
    description: "Rating Service Client Secret"
    required: false
  sendgrid-api-key:
    description: "SendGrid API Key"
    required: false
  sendgrid-email:
    description: "SendGrid Email"
    required: false
  sendgrid-sender-name:
    description: "SendGrid Sender Name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ${{ inputs.bun-version-file }}

    - name: Cache Aspire CLI
      id: cache-aspire
      uses: actions/cache@v4
      with:
        path: ~/.aspire
        key: ${{ inputs.operations-environment }}-aspire-cli
        restore-keys: |
          ${{ inputs.operations-environment }}-aspire-

    - name: Install Aspire CLI
      if: steps.cache-aspire.outputs.cache-hit != 'true'
      shell: bash
      run: curl -sSL https://aspire.dev/install.sh | bash -s -- -q dev

    - name: Add Aspire CLI to PATH
      shell: bash
      run: echo "$HOME/.aspire/bin" >> $GITHUB_PATH

    - name: Verify Aspire Installation
      shell: bash
      run: aspire --version

    - name: Push to GitHub Container Registry
      shell: bash
      run: aspire do push
      env:
        Parameters__container_endpoint: ghcr.io
        Parameters__container_repository: ${{ inputs.repository-owner }}/${{ inputs.repository-name }}
        Parameters__openai_openai_apikey: ${{ inputs.openai-apikey }}
        Parameters__kc_url: ${{ inputs.kc-url }}
        Parameters__kc_realm: ${{ inputs.kc-realm }}
        Parameters__catalog_secret: ${{ inputs.catalog-secret }}
        Parameters__basket_secret: ${{ inputs.basket-secret }}
        Parameters__ordering_secret: ${{ inputs.ordering-secret }}
        Parameters__chatting_secret: ${{ inputs.chatting-secret }}
        Parameters__rating_secret: ${{ inputs.rating-secret }}
        Parameters__sendgrid_api_key: ${{ inputs.sendgrid-api-key }}
        Parameters__sendgrid_email: ${{ inputs.sendgrid-email }}
        Parameters__sendgrid_sender_name: ${{ inputs.sendgrid-sender-name }}
