name: "Publish Artifact"
description: "Publish the artifact to GitHub Container Registry"

inputs:
  global-json-file:
    description: "The path to the global.json file"
    required: false
    default: "./global.json"
  bun-version-file:
    description: "The path to the .bun-version file"
    required: false
    default: ".bun-version"
  repository-owner:
    description: "The owner of the repository"
    required: true
    default: "${{ github.repository_owner }}"
  repository-name:
    description: "The name of the repository"
    required: true
    default: "${{ github.event.repository.name }}"
  container-tag:
    description: "The tag for the container image"
    required: true
    default: "latest"
  operations-environment:
    description: "The operations environment to use for Aspire commands"
    required: false
    default: ${{ runner.os }}

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ${{ inputs.bun-version-file }}

    - name: Cache Aspire CLI
      id: cache-aspire
      uses: actions/cache@v5
      with:
        path: ~/.aspire
        key: ${{ inputs.operations-environment }}-aspire-cli
        restore-keys: |
          ${{ inputs.operations-environment }}-aspire-

    - name: Install Aspire CLI
      if: steps.cache-aspire.outputs.cache-hit != 'true'
      shell: bash
      run: curl -sSL https://aspire.dev/install.sh | bash -s -- -q dev

    - name: Add Aspire CLI to PATH
      shell: bash
      run: echo "$HOME/.aspire/bin" >> $GITHUB_PATH

    - name: Verify Aspire Installation
      shell: bash
      run: aspire --version

    - name: Push to GitHub Container Registry
      shell: bash
      run: aspire do push-gh
      env:
        CONTAINER_TAG: ${{ inputs.container-tag }}
        GHCR_ORGANIZATION: ${{ inputs.repository-owner }}
        GHCR_REPOSITORY: ${{ inputs.repository-name }}
