name: "Publish Artifact"
description: "Publish the artifact to GitHub Container Registry"

inputs:
  global-json-file:
    description: "The path to the global.json file"
    required: false
    default: "./global.json"
  bun-version-file:
    description: "The path to the .bun-version file"
    required: false
    default: ".bun-version"
  project-path:
    description: "The path to the project file"
    required: true
  container-repository:
    description: "The name of the container repository"
    required: true
  container-tag:
    description: "The tag for the container image"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ${{ inputs.bun-version-file }}

    - name: Build
      shell: bash
      run: |
        dotnet build ${{ inputs.project-path }} --configuration Release

    - name: Publish
      shell: bash
      run: >
        dotnet publish ${{ inputs.project-path }}
        -t:PublishContainer
        --verbosity "quiet"
        --nologo
        -r "linux-x64"
        -p:ContainerRegistry="ghcr.io"
        -p:ContainerRepository="${{ inputs.container-repository }}"
        -p:ContainerImageTag="${{ inputs.container-tag }}"
