---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "keycloak-config"
  labels:
    app: "aspire"
    component: "keycloak"
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.config.keycloak.KC_BOOTSTRAP_ADMIN_USERNAME }}"
  KC_HEALTH_ENABLED: "{{ .Values.config.keycloak.KC_HEALTH_ENABLED }}"
