---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "keycloak-secrets"
  labels:
    app: "aspire"
    component: "keycloak"
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.secrets.keycloak.keycloak_password }}"
type: "Opaque"
