---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "keycloak-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "keycloak"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "8080"
      targetPort: "8080"
    - name: "management"
      protocol: "TCP"
      port: "9000"
      targetPort: "9000"
