graph TD
	QHZT("@bookworm/backoffice#build") --> ETTT("@workspace/ui#build")
	JEGP("@bookworm/storefront#build") --> EMLE("@workspace/eslint-config#build")
	JEGP("@bookworm/storefront#build") --> LRHC("@workspace/typescript-config#build")
	GLAO("@workspace/api-client#build") --> EMLE("@workspace/eslint-config#build")
	GLAO("@workspace/api-client#build") --> LRHC("@workspace/typescript-config#build")
	VELR("@workspace/api-hooks#build") --> GLAO("@workspace/api-client#build")
	VELR("@workspace/api-hooks#build") --> EMLE("@workspace/eslint-config#build")
	VELR("@workspace/api-hooks#build") --> TXWC("@workspace/types#build")
	VELR("@workspace/api-hooks#build") --> LRHC("@workspace/typescript-config#build")
	EMLE("@workspace/eslint-config#build") --> WCIN("___ROOT___")
	TPBW("@workspace/mocks#build") --> EMLE("@workspace/eslint-config#build")
	TPBW("@workspace/mocks#build") --> LRHC("@workspace/typescript-config#build")
	TXWC("@workspace/types#build") --> EMLE("@workspace/eslint-config#build")
	TXWC("@workspace/types#build") --> LRHC("@workspace/typescript-config#build")
	LRHC("@workspace/typescript-config#build") --> WCIN("___ROOT___")
	ETTT("@workspace/ui#build") --> EMLE("@workspace/eslint-config#build")
	ETTT("@workspace/ui#build") --> LRHC("@workspace/typescript-config#build")
	BHWE("@workspace/utils#build") --> WCIN("___ROOT___")
	MKNG("@workspace/validations#build") --> EMLE("@workspace/eslint-config#build")
	MKNG("@workspace/validations#build") --> LRHC("@workspace/typescript-config#build")
