packages:
  - "apps/*"
  - "packages/*"

peerDependencyRules:
  allowAny:
    - "eslint"
    - "@ag-ui/*"
    - "openai"
    - "backbone"
    - "underscore"
  ignoreMissing:
    - "backbone"
    - "underscore"
