---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "vector-db-secrets"
  labels:
    app: "aspire"
    component: "vector-db"
stringData:
  QDRANT__SERVICE__API_KEY: "{{ .Values.secrets.vector-db.vector_db_Key }}"
type: "Opaque"
