---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "vector-db-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "vector-db"
  ports:
    - name: "grpc"
      protocol: "TCP"
      port: "6334"
      targetPort: "6334"
    - name: "http"
      protocol: "TCP"
      port: "6333"
      targetPort: "6333"
