---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: catalog-api
          resources:
            limits:
              memory: 512Mi
          image: catalog-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: catalog-api-env
            - secretRef:
                name: catalog-api-secrets
      terminationGracePeriodSeconds: 180
