resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: catalog-api-env
    literals:
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - AiOptions__OpenAi__EmbeddingName=text-embedding-3-small
      - AzuriteOptions__ConnectionString={storage.outputs.blobEndpoint}
      - ASPNETCORE_HTTP_PORTS=8080;8081
      - HEALTHCHECKSUI_URLS=catalog-api:8081/healthz
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_SERVICE_NAME=catalog-api
      - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
  - name: catalog-api-secrets
    envs:
      - .catalog-api.secrets
