---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  labels:
    app: ordering-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ordering-api
          resources:
            limits:
              memory: 512Mi
          image: ordering-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: ordering-api-env
            - secretRef:
                name: ordering-api-secrets
      terminationGracePeriodSeconds: 180
