parameters:
  bookworm-catalog:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_catalog_image: "bookworm-catalog:latest"
  bookworm-basket:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_basket_image: "bookworm-basket:latest"
  bookworm-notification:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_notification_image: "bookworm-notification:latest"
  bookworm-ordering:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_ordering_image: "bookworm-ordering:latest"
  bookworm-rating:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_rating_image: "bookworm-rating:latest"
  bookworm-finance:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_finance_image: "bookworm-finance:latest"
  bookworm-gateway:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    bookworm_gateway_image: "bookworm-gateway:latest"
secrets:
  vector-db:
    QDRANT__SERVICE__API_KEY: ""
  queue:
    RABBITMQ_DEFAULT_PASS: ""
  keycloak:
    KC_BOOTSTRAP_ADMIN_PASSWORD: ""
  bookworm-notification:
    SendGrid__ApiKey: ""
    SendGrid__SenderEmail: ""
    SendGrid__SenderName: ""
config:
  vector-db:
    QDRANT__SERVICE__ENABLE_STATIC_CONTENT: "0"
  queue:
    RABBITMQ_DEFAULT_USER: "guest"
  keycloak:
    KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
    KC_HEALTH_ENABLED: "true"
  bookworm-catalog:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__blob: "{storage.outputs.blobEndpoint}"
    ConnectionStrings__catalogdb: "{postgres.outputs.connectionString};Database=catalogdb"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
    ConnectionStrings__redis: "{redis.outputs.connectionString}"
    ConnectionStrings__signalr: "Endpoint=https://{signalr.outputs.hostName};AuthType=azure"
    ConnectionStrings__embedding: "Endpoint=http://ollama:11434;Model=nomic-embed-text:latest"
    ConnectionStrings__chat: "Endpoint=http://ollama:11434;Model=deepseek-r1:1.5b"
  bookworm-basket:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__redis: "{redis.outputs.connectionString}"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  bookworm-notification:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  bookworm-ordering:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__orderingdb: "{postgres.outputs.connectionString};Database=orderingdb"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
    ConnectionStrings__redis: "{redis.outputs.connectionString}"
  bookworm-rating:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__cosmos: "{cosmos.outputs.connectionString}"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  bookworm-finance:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__financedb: "{postgres.outputs.connectionString};Database=financedb"
  bookworm-gateway:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  health-checks-ui:
    ui_path: "/"
    HealthChecksUI__HealthChecks__0__Name: "bookworm-gateway"
    HealthChecksUI__HealthChecks__1__Name: "bookworm-catalog"
    HealthChecksUI__HealthChecks__2__Name: "bookworm-ordering"
    HealthChecksUI__HealthChecks__3__Name: "bookworm-rating"
    HealthChecksUI__HealthChecks__4__Name: "bookworm-basket"
    HealthChecksUI__HealthChecks__5__Name: "bookworm-notification"
    HealthChecksUI__HealthChecks__6__Name: "bookworm-finance"
