parameters:
  catalog:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    catalog_image: "catalog:latest"
  mcptools:
    port_http: "8080"
    port_https: "8080"
    mcptools_image: "mcptools:latest"
  chatting:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    chatting_image: "chatting:latest"
  basket:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    basket_image: "basket:latest"
  notification:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    notification_image: "notification:latest"
  ordering:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    ordering_image: "ordering:latest"
  rating:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    rating_image: "rating:latest"
  finance:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    finance_image: "finance:latest"
  gateway:
    port_http: "8080"
    port_https: "8080"
    port_healthchecks: "8080"
    gateway_image: "gateway:latest"
secrets:
  vectordb:
    QDRANT__SERVICE__API_KEY: ""
  queue:
    RABBITMQ_DEFAULT_PASS: ""
  keycloak:
    KC_BOOTSTRAP_ADMIN_PASSWORD: ""
  notification:
    SendGrid__ApiKey: ""
    SendGrid__SenderEmail: ""
    SendGrid__SenderName: ""
config:
  vectordb:
    QDRANT__SERVICE__ENABLE_STATIC_CONTENT: "0"
  queue:
    RABBITMQ_DEFAULT_USER: "guest"
  keycloak:
    KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
    KC_HEALTH_ENABLED: "true"
  catalog:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__embedding: "Endpoint=http://ollama:11434;Model=nomic-embed-text:latest"
    ConnectionStrings__chat: "Endpoint=http://ollama:11434;Model=deepseek-r1:1.5b"
    ConnectionStrings__blob: "{storage.outputs.blobEndpoint}"
    ConnectionStrings__catalogdb: "{postgres-kv.secrets.connectionstrings--catalogdb}"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
    ConnectionStrings__redis: "{redis-kv.secrets.connectionstrings--redis}"
  mcptools:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__embedding: "Endpoint=http://ollama:11434;Model=nomic-embed-text:latest"
    ConnectionStrings__chat: "Endpoint=http://ollama:11434;Model=deepseek-r1:1.5b"
  chatting:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__embedding: "Endpoint=http://ollama:11434;Model=nomic-embed-text:latest"
    ConnectionStrings__chat: "Endpoint=http://ollama:11434;Model=deepseek-r1:1.5b"
    ConnectionStrings__redis: "{redis-kv.secrets.connectionstrings--redis}"
    ConnectionStrings__signalr: "Endpoint=https://{signalr.outputs.hostName};AuthType=azure"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  basket:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__redis: "{redis-kv.secrets.connectionstrings--redis}"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  notification:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__table: "{storage.outputs.tableEndpoint}"
  ordering:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__orderingdb: "{postgres-kv.secrets.connectionstrings--orderingdb}"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
    ConnectionStrings__redis: "{redis-kv.secrets.connectionstrings--redis}"
  rating:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__ratingdb: "{postgres-kv.secrets.connectionstrings--ratingdb}"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  finance:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__financedb: "{postgres-kv.secrets.connectionstrings--financedb}"
  gateway:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    services__keycloak__http__0: "http://keycloak:8080"
    services__keycloak__management__0: "http://keycloak:9000"
  health-checks-ui:
    ui_path: "/"
    HealthChecksUI__HealthChecks__0__Name: "gateway"
    HealthChecksUI__HealthChecks__1__Name: "catalog"
    HealthChecksUI__HealthChecks__2__Name: "chatting"
    HealthChecksUI__HealthChecks__3__Name: "ordering"
    HealthChecksUI__HealthChecks__4__Name: "rating"
    HealthChecksUI__HealthChecks__5__Name: "basket"
    HealthChecksUI__HealthChecks__6__Name: "notification"
    HealthChecksUI__HealthChecks__7__Name: "finance"
