---
apiVersion: v1
kind: Service
metadata:
  name: vector-db
spec:
  type: ClusterIP
  selector:
    app: vector-db
  ports:
    - name: grpc
      port: 6334
      targetPort: 6334
    - name: http
      port: 6333
      targetPort: 6333
