---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-db
  labels:
    app: vector-db
spec:
  serviceName: "vector-db"
  replicas: 1
  selector:
    matchLabels:
      app: vector-db
  template:
    metadata:
      labels:
        app: vector-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: vector-db
          image: docker.io/qdrant/qdrant:v1.12.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6334
            - containerPort: 6333
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 2Gi
          envFrom:
            - configMapRef:
                name: vector-db-env
          volumeMounts:
            - name: bookworm-apphost-62fd53aa4e-vector-db-data
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: bookworm-apphost-62fd53aa4e-vector-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
