---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          resources:
            limits:
              memory: 512Mi
          image: docker.io/ankane/pgvector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-env
            - secretRef:
                name: postgres-secrets
      terminationGracePeriodSeconds: 180
