global using System.Security.Claims;
global using System.Threading.RateLimiting;
global using BookWorm.Gateway;
global using BookWorm.ServiceDefaults;
global using Duende.Bff;
global using Duende.Bff.Yarp;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authentication.OpenIdConnect;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
