---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "bookworm-catalog-deployment"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "bookworm-catalog"
    spec:
      containers:
        - image: "{{ .Values.parameters.bookworm-catalog.bookworm_catalog_image }}"
          name: "bookworm-catalog"
          envFrom:
            - configMapRef:
                name: "bookworm-catalog-config"
            - secretRef:
                name: "bookworm-catalog-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.bookworm-catalog.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.bookworm-catalog.port_https }}"
            - name: "healthchecks"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.bookworm-catalog.port_healthchecks }}"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app: "aspire"
      component: "bookworm-catalog"
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
