---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bookworm-catalog-secrets"
  labels:
    app: "aspire"
    component: "bookworm-catalog"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.bookworm-catalog.queue_password }}@queue:5672"
  ConnectionStrings__vector_db: "Endpoint=http://vector-db:6334;Key={{ .Values.secrets.bookworm-catalog.vector_db_Key }}"
  ConnectionStrings__vector_db_http: "Endpoint=http://vector-db:6333;Key={{ .Values.secrets.bookworm-catalog.vector_db_Key }}"
type: "Opaque"
