---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "bookworm-rating-config"
  labels:
    app: "aspire"
    component: "bookworm-rating"
data:
  ASPNETCORE_URLS: "{{ .Values.config.bookworm-rating.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-rating.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.bookworm-rating.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.bookworm-rating.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.bookworm-rating.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.bookworm-rating.HTTP_PORTS }}"
  ConnectionStrings__cosmos: "{{ .Values.config.bookworm-rating.ConnectionStrings__cosmos }}"
  services__keycloak__http__0: "{{ .Values.config.bookworm-rating.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.bookworm-rating.services__keycloak__management__0 }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.bookworm-rating.HEALTHCHECKSUI_URLS }}"
