---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bookworm-rating-secrets"
  labels:
    app: "aspire"
    component: "bookworm-rating"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.bookworm-rating.queue_password }}@queue:5672"
type: "Opaque"
