---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-finance
  labels:
    app: bookworm-finance
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: bookworm-finance
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookworm-finance
    spec:
      automountServiceAccountToken: false
      containers:
        - name: bookworm-finance
          image: ghcr.io/foxminchan/bookworm/finance:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8005
          livenessProbe:
            httpGet:
              path: /
              port: healthchecks
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /alive
              port: healthchecks
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: "1500m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
          envFrom:
            - configMapRef:
                name: bookworm-finance-env
            - secretRef:
                name: bookworm-finance-secrets
      terminationGracePeriodSeconds: 180
