---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "queue-config"
  labels:
    app: "aspire"
    component: "queue"
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.config.queue.RABBITMQ_DEFAULT_USER }}"
