---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "queue-secrets"
  labels:
    app: "aspire"
    component: "queue"
stringData:
  RABBITMQ_DEFAULT_PASS: "{{ .Values.secrets.queue.queue_password }}"
type: "Opaque"
