---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "queue-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "queue"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: "5672"
      targetPort: "5672"
    - name: "management"
      protocol: "TCP"
      port: "15672"
      targetPort: "15672"
