---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "queue-statefulset"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "queue"
    spec:
      containers:
        - image: "docker.io/library/rabbitmq:4.0-management"
          name: "queue"
          envFrom:
            - configMapRef:
                name: "queue-config"
            - secretRef:
                name: "queue-secrets"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: "5672"
            - name: "management"
              protocol: "TCP"
              containerPort: "15672"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app: "aspire"
      component: "queue"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
