---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "catalog-config"
  labels:
    app: "aspire"
    component: "catalog"
data:
  ASPNETCORE_URLS: "{{ .Values.config.catalog.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.catalog.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.catalog.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.catalog.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.catalog.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.catalog.HTTP_PORTS }}"
  ConnectionStrings__embedding: "{{ .Values.config.catalog.ConnectionStrings__embedding }}"
  ConnectionStrings__chat: "{{ .Values.config.catalog.ConnectionStrings__chat }}"
  ConnectionStrings__blob: "{{ .Values.config.catalog.ConnectionStrings__blob }}"
  ConnectionStrings__catalogdb: "{{ .Values.config.catalog.ConnectionStrings__catalogdb }}"
  services__keycloak__http__0: "{{ .Values.config.catalog.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.catalog.services__keycloak__management__0 }}"
  ConnectionStrings__redis: "{{ .Values.config.catalog.ConnectionStrings__redis }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.catalog.HEALTHCHECKSUI_URLS }}"
