global using BookWorm.Chassis.Endpoints;
global using BookWorm.Chassis.Exceptions;
global using BookWorm.Chat.Infrastructure;
global using BookWorm.Constants.Aspire;
global using BookWorm.Constants.Core;
global using BookWorm.ServiceDefaults.ApiSpecification.OpenApi;
global using BookWorm.ServiceDefaults.Kestrel;
global using Microsoft.Extensions.AI;
global using ModelContextProtocol.Client;
