<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\tests\BookWorm.Testing\BookWorm.Testing.csproj" />
    <ProjectReference Include="..\BookWorm.McpTools\BookWorm.McpTools.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Moq" />
    <Using Include="Bogus" />
    <Using Include="Shouldly" />
  </ItemGroup>
</Project>
