apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: eventbus
  name: eventbus
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: eventbus
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: eventbus
        image: '{{ .Values.images.eventbus }}'
        imagePullPolicy: IfNotPresent
        name: eventbus
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: management
      terminationGracePeriodSeconds: 180