apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: eventbus
  name: eventbus
spec:
  ports:
  - name: tcp
    port: 5672
    targetPort: 0
  - name: management
    port: 15672
    targetPort: 0
  selector:
    app: eventbus
  type: ClusterIP