apiVersion: v1
data:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: sF0LCfbagthqFVoUgmYWPB
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: eventbus
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: eventbus
  name: eventbus