apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: healthchecksui
  name: healthchecksui
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: healthchecksui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: healthchecksui
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: healthchecksui
        image: '{{ .Values.images.healthchecksui }}'
        imagePullPolicy: IfNotPresent
        name: healthchecksui
        ports:
        - containerPort: 80
          name: http
      terminationGracePeriodSeconds: 180