apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: healthchecksui
  name: healthchecksui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 0
  selector:
    app: healthchecksui
  type: ClusterIP