apiVersion: v1
data:
  ConnectionStrings__identitydb: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM7RGF0YWJhc2U9aWRlbnRpdHlkYg==
  ConnectionStrings__redis: cmVkaXM6NjM3OQ==
kind: Secret
metadata:
  annotations: {}
  labels:
    app: identity-api
  name: identity-api
type: Opaque