apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: identity-api
  name: identity-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 0
  - name: https
    port: 8443
    targetPort: 0
  - name: healthchecks
    port: 8081
    targetPort: 0
  selector:
    app: identity-api
  type: ClusterIP