apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mailserver
  name: mailserver
spec:
  ports:
  - name: http
    port: 1080
    targetPort: 0
  - name: smtp
    port: 1025
    targetPort: 0
  selector:
    app: mailserver
  type: ClusterIP