apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: mailserver
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: mailserver
  name: mailserver