apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: mailserver
  name: mailserver
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: mailserver
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: mailserver
        image: '{{ .Values.images.mailserver }}'
        imagePullPolicy: IfNotPresent
        name: mailserver
        ports:
        - containerPort: 1080
          name: http
        - containerPort: 1025
          name: smtp
      terminationGracePeriodSeconds: 180