apiVersion: v1
data:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: hbYUNnvyPKe95mH1P8FtUv
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: mongodb
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: mongodb
  name: mongodb