apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: mongodb
  name: mongodb
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: mongodb
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: mongodb
        image: '{{ .Values.images.mongodb }}'
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          name: tcp
      terminationGracePeriodSeconds: 180