apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: postgres
  name: postgres
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: postgres
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: postgres
        - secretRef:
            name: postgres
        image: '{{ .Values.images.postgres }}'
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          name: tcp
      terminationGracePeriodSeconds: 180