apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: 0
  selector:
    app: postgres
  type: ClusterIP