apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: rating-api
  name: rating-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: rating-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: rating-api
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: rating-api
        - secretRef:
            name: rating-api
        image: '{{ .Values.images.ratingapi }}'
        imagePullPolicy: IfNotPresent
        name: rating-api
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 8081
          name: healthchecks
      terminationGracePeriodSeconds: 180