apiVersion: v1
data:
  ConnectionStrings__eventbus: YW1xcDovL2d1ZXN0OnNGMExDZmJhZ3RocUZWb1VnbVlXUEJAZXZlbnRidXM6NTY3Mg==
  ConnectionStrings__ratingdb: bW9uZ29kYjovL2FkbWluOmhiWVVObnZ5UEtlOTVtSDFQOEZ0VXZAbW9uZ29kYjoyNzAxNy9yYXRpbmdkYj9hdXRoU291cmNlPWFkbWluJmF1dGhNZWNoYW5pc209U0NSQU0tU0hBLTI1Ng==
  ConnectionStrings__redis: cmVkaXM6NjM3OQ==
kind: Secret
metadata:
  annotations: {}
  labels:
    app: rating-api
  name: rating-api
type: Opaque