apiVersion: v1
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  HTTP_PORTS: 8080;8081
  ASPNETCORE_HTTP_PORTS: 8080;8081
  HEALTHCHECKSUI_URLS: rating-api:8081/healthz
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: rating-api
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: rating-api
  name: rating-api