apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: redis
  name: redis
spec:
  ports:
  - name: tcp
    port: 6379
    targetPort: 0
  selector:
    app: redis
  type: ClusterIP