---
openapi: 3.0.1
info:
  title: Finance Service
  version: 1.0.0
  description: |-
    Finance API for BookWorm
  contact:
    name: Nhan Nguyen
    url: https://github.com/foxminchan
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:54684
paths:
  "/api/v1/order-state-machine":
    get:
      tags:
        - OrderState
      summary: Get order state machine
      description: Get order state machine from orchestrator
      x-eventcatalog-message-type: query
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
tags:
  - name: OrderState
