name: "Scan"
description: "Scan the repository for secrets and other security issues"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Gitleaks with Docker
      shell: bash
      run: |
        docker run --rm -v $(pwd):/repo ghcr.io/gitleaks/gitleaks:latest detect --source=/repo --exit-code 1
