---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecksui
  labels:
    app: healthchecksui
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: healthchecksui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: healthchecksui
    spec:
      automountServiceAccountToken: false
      containers:
        - name: healthchecksui
          image: docker.io/xabarilcoding/healthchecksui:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            requests:
              cpu: "100m"
              memory: "64Mi"
              ephemeral-storage: "512Mi"
          envFrom:
            - configMapRef:
                name: healthchecksui-env
      terminationGracePeriodSeconds: 180
