resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: healthchecksui-env
    literals:
      - ui_path=/
      - HealthChecksUI__HealthChecks__0__Name=bookworm-gateway
      - HealthChecksUI__HealthChecks__0__Uri=bookworm-gateway:8006/healthz
      - HealthChecksUI__HealthChecks__1__Name=bookworm-catalog
      - HealthChecksUI__HealthChecks__1__Uri=bookworm-catalog:8000/healthz
      - HealthChecksUI__HealthChecks__2__Name=bookworm-ordering
      - HealthChecksUI__HealthChecks__2__Uri=bookworm-ordering:8003/healthz
      - HealthChecksUI__HealthChecks__3__Name=bookworm-rating
      - HealthChecksUI__HealthChecks__3__Uri=bookworm-rating:8004/healthz
      - HealthChecksUI__HealthChecks__4__Name=bookworm-basket
      - HealthChecksUI__HealthChecks__4__Uri=bookworm-basket:8001/healthz
      - HealthChecksUI__HealthChecks__5__Name=bookworm-notification
      - HealthChecksUI__HealthChecks__5__Uri=bookworm-notification:8002/healthz
      - HealthChecksUI__HealthChecks__6__Name=bookworm-finance
      - HealthChecksUI__HealthChecks__6__Uri=bookworm-finance:8005/healthz
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_SERVICE_NAME=healthchecksui
