---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-notification
  labels:
    app: bookworm-notification
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: bookworm-notification
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookworm-notification
    spec:
      automountServiceAccountToken: false
      containers:
        - name: bookworm-notification
          image: ghcr.io/foxminchan/bookworm/notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: healthchecks
              containerPort: 8002
          livenessProbe:
            httpGet:
              path: /health
              port: healthchecks
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /alive
              port: healthchecks
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          envFrom:
            - configMapRef:
                name: bookworm-notification-env
            - secretRef:
                name: bookworm-notification-secrets
      terminationGracePeriodSeconds: 180
