---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: docker.io/axllent/mailpit:v1.22.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 1025
            - name: http
              containerPort: 8025
          envFrom:
            - configMapRef:
                name: mailpit-env
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
      terminationGracePeriodSeconds: 180
