name: "Analyzers"
description: "Analyze the repository using Husky"

inputs:
  global-json-file:
    description: "The path to the global.json file"
    required: false
    default: "./global.json"

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Install Tools
      shell: bash
      run: dotnet tool restore

    - name: Configure Husky
      shell: bash
      if: success()
      run: dnx husky install

    - name: Run Analyzers Task
      shell: bash
      if: success()
      run: dnx husky run --name analyzers
