name: BookWorm Clean Up
run-name: Delete untagged package versions

on:
  workflow_dispatch:
  schedule:
    # Runs bi-weekly on Monday at 10:00 AM Asia/Ho_Chi_Minh (UTC+7)
    - cron: "0 3 1-7,15-21 * 1"

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  delete-package-versions:
    name: Delete untagged package versions
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write
    strategy:
      matrix:
        image:
          - bookworm/basket
          - bookworm/catalog
          - bookworm/chatting
          - bookworm/finance
          - bookworm/gateway
          - bookworm/mcptools
          - bookworm/notification
          - bookworm/ordering
          - bookworm/rating
          - bookworm/scheduler
          - bookworm/storefront
          - bookworm/backoffice
    steps:
      - uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb # v3.0.1
        with:
          account: user
          token: ${{ github.token }}
          image-names: ${{ matrix.image }}
          tag-selection: untagged
          timestamp-to-use: created_at
          cut-off: 1w
          keep-n-most-recent: 3
