name: BookWorm CI (.NET)
run-name: .NET CI - ${{ github.event_name }} by ${{ github.actor }}

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/ci.yaml"
      - ".github/actions/**"
      - "Directory.Packages.props"
      - "Directory.Build.props"
      - "global.json"
      - "Versions.props"
      - ".config/dotnet-tools.json"
      - "!**.md"
      - "!src/Aspire/BookWorm.AppHost/Container/**"
      - "BookWorm.slnx"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: environment
      publish:
        description: "Whether to publish the artifacts"
        type: boolean
        required: true
        default: true

env:
  GLOBAL_JSON_PATH: ${{ github.workspace }}/global.json
  BUN_VERSION_FILE: ${{ github.workspace }}/.bun-version

permissions:
  checks: write
  pull-requests: write
  security-events: write
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Cache .NET SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.dotnet
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/global.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Security Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Format
        uses: ./.github/actions/format
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

  style:
    name: Style
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Style
        uses: ./.github/actions/style
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

  analyzers:
    name: Analyzers
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Analyzers
        uses: ./.github/actions/analyzers
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup, security-scan, format, style, analyzers]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup, security-scan, format, style, analyzers]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/test
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

  publish:
    name: Publish Artifacts
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish || false
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        service:
          - name: "Basket"
            project-path: "src/Services/Basket/BookWorm.Basket/BookWorm.Basket.csproj"
            container-repository: "foxminchan/bookworm/basket"
          - name: "Catalog"
            project-path: "src/Services/Catalog/BookWorm.Catalog/BookWorm.Catalog.csproj"
            container-repository: "foxminchan/bookworm/catalog"
          - name: "Finance"
            project-path: "src/Services/Finance/BookWorm.Finance/BookWorm.Finance.csproj"
            container-repository: "foxminchan/bookworm/finance"
          - name: "Notification"
            project-path: "src/Services/Notification/BookWorm.Notification/BookWorm.Notification.csproj"
            container-repository: "foxminchan/bookworm/notification"
          - name: "Ordering"
            project-path: "src/Services/Ordering/BookWorm.Ordering/BookWorm.Ordering.csproj"
            container-repository: "foxminchan/bookworm/ordering"
          - name: "Rating"
            project-path: "src/Services/Rating/BookWorm.Rating/BookWorm.Rating.csproj"
            container-repository: "foxminchan/bookworm/rating"
          - name: "Chat"
            project-path: "src/Services/Chat/BookWorm.Chat/BookWorm.Chat.csproj"
            container-repository: "foxminchan/bookworm/chat"
          - name: "MCP Tools"
            project-path: "src/Integrations/BookWorm.McpTools/BookWorm.McpTools.csproj"
            container-repository: "foxminchan/bookworm/mcptools"
          - name: "Scheduler"
            project-path: "src/Services/Scheduler/BookWorm.Scheduler/BookWorm.Scheduler.csproj"
            container-repository: "foxminchan/bookworm/scheduler"
          - name: "Scheduler Migrator"
            project-path: "src/Services/Scheduler/BookWorm.Scheduler.Migrator/BookWorm.Scheduler.Migrator.csproj"
            container-repository: "foxminchan/bookworm/scheduler-migrator"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'development' }}
    timeout-minutes: 15
    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set tag version
        id: set_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish ${{ matrix.service.name }} Service
        uses: ./.github/actions/publish
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}
          bun-version-file: ${{ env.BUN_VERSION_FILE }}
          project-path: ${{ matrix.service.project-path }}
          container-repository: ${{ matrix.service.container-repository }}
          container-tag: ${{ steps.set_tag.outputs.version }}
