name: .NET Coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          include-prerelease: true

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Build & Restore
        run: dotnet build

      - name: Test
        run: dotnet test --no-build --settings CodeCoverage.runsettings --results-directory ./coverage

      - name: Publish Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/*.cobertura.xml
          badge: true
          format: markdown

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
